#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │       Compiling Rebalancer contracts...      │"
echo " └──────────────────────────────────────────────┘"

SOLC_VERSION="0.8.19"
OPTIMIZE_RUNS=1000000


SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
python3 -m pip install --require-hashes -r "$SCRIPTPATH"/requirements.txt
solc-select install $SOLC_VERSION
solc-select use $SOLC_VERSION
export SOLC_VERSION=$SOLC_VERSION

ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../../ && pwd -P )"

compileContract () {
  local contract
  contract=$(basename "$1" ".sol")

  solc @arbitrum/="$ROOT"/contracts/node_modules/@arbitrum/ \
       @eth-optimism/="$ROOT"/contracts/node_modules/@eth-optimism/ \
       @openzeppelin/="$ROOT"/contracts/node_modules/@openzeppelin/ \
       --overwrite --optimize --optimize-runs $OPTIMIZE_RUNS --metadata-hash none \
      -o "$ROOT"/contracts/solc/v$SOLC_VERSION/"$contract" \
      --abi --bin --allow-paths "$ROOT"/contracts/src/v0.8,"$ROOT"/contracts/node_modules \
      "$ROOT"/contracts/src/v0.8/"$1"
}


# Liquidity Management
compileContract rebalancer/Rebalancer.sol
compileContract rebalancer/bridge-adapters/ArbitrumL1BridgeAdapter.sol
compileContract rebalancer/bridge-adapters/ArbitrumL2BridgeAdapter.sol
compileContract rebalancer/bridge-adapters/OptimismL1BridgeAdapter.sol
compileContract rebalancer/bridge-adapters/OptimismL2BridgeAdapter.sol
compileContract rebalancer/test/mocks/NoOpOCR3.sol
compileContract rebalancer/test/mocks/MockBridgeAdapter.sol
compileContract rebalancer/test/helpers/RebalancerReportEncoder.sol

# Arbitrum helpers
compileContract rebalancer/interfaces/arbitrum/IArbSys.sol
compileContract rebalancer/interfaces/arbitrum/INodeInterface.sol
compileContract rebalancer/interfaces/arbitrum/IL2ArbitrumGateway.sol
compileContract rebalancer/interfaces/arbitrum/IL2ArbitrumMessenger.sol
compileContract rebalancer/interfaces/arbitrum/IArbRollupCore.sol
compileContract rebalancer/interfaces/arbitrum/IArbitrumL1GatewayRouter.sol
compileContract rebalancer/interfaces/arbitrum/IArbitrumInbox.sol
compileContract rebalancer/interfaces/arbitrum/IArbitrumGatewayRouter.sol
compileContract rebalancer/interfaces/arbitrum/IArbitrumTokenGateway.sol
compileContract rebalancer/interfaces/arbitrum/IAbstractArbitrumTokenGateway.sol
