#!/usr/bin/env bash

# This script generates .abi and .bin files for a selected .sol contract.
# Example call:
#   ./contracts/scripts/native_solc_compile dev/Operator.sol
#
# The resulting abi and bin files are stored in ./contracts/solc/v0.8

ROOT="$(
    cd "$(dirname "$0")" >/dev/null 2>&1
    cd ../../ && pwd -P
)"

solc-select use 0.8.15
solc @openzeppelin/=$ROOT/contracts/node_modules/@openzeppelin/ --overwrite --optimize --optimize-runs 1000 --metadata-hash none \
    -o $ROOT/contracts/solc/v0.8.15 \
    --abi --bin \
    --allow-paths $ROOT/contracts/src/v0.8,$ROOT/contracts/src/v0.8/dev,$ROOT/contracts/src/v0.8/interfaces,$ROOT/contracts/src/v0.8/mocks,$ROOT/contracts/src/v0.8/tests,$ROOT/contracts/src/v0.8/vendor,$ROOT/contracts/node_modules/.pnpm/@openzeppelin+contracts@4.3.3/node_modules/@openzeppelin/contracts,$ROOT/contracts/node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable \
    $ROOT/contracts/src/v0.8/$1
