#!/usr/bin/env bash

set -e

SOLC_VERSION="0.8.15"
OPTIMIZE_RUNS=15000


SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
python3 -m pip install --require-hashes -r $SCRIPTPATH/requirements.txt
solc-select install $SOLC_VERSION
solc-select use $SOLC_VERSION
export SOLC_VERSION=$SOLC_VERSION

ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../../ && pwd -P )"

compileContract () {
  solc --overwrite --optimize --optimize-runs $OPTIMIZE_RUNS --metadata-hash none \
      -o $ROOT/contracts/solc/v$SOLC_VERSION \
      --abi --bin --allow-paths $ROOT/contracts/src/v0.8 \
      $ROOT/contracts/src/v0.8/$1
}

# Contracts
compileContract metatx/Forwarder.sol
compileContract metatx/BankERC20.sol
