#!/usr/bin/env bash

set -e

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo $SCRIPTPATH
python3 -m pip install --require-hashes -r $SCRIPTPATH/requirements.txt
solc-select install 0.8.15

# OCR2VRF
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/DKG.sol
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/VRFBeacon.sol
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/VRFCoordinator.sol
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/VRFRouter.sol
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/TestBeaconVRFConsumer.sol
$SCRIPTPATH/native_solc8_15_compile_ocr2vrf ../../../../ocr2vrf-origin/contracts/LoadTestBeaconVRFConsumer.sol
