#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │        Compiling OCR2 VRF contracts...       │"
echo " └──────────────────────────────────────────────┘"

SOLC_VERSION="0.8.19"
OPTIMIZE_RUNS=1000000
# The VRF contracts are not contained in the `chainlink` repository.
# Change me.
FOLDER="ocr2vrf-origin"

echo "Compiling OCR2VRF contracts..."

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1; cd ../../ && pwd -P )"
python3 -m pip install --require-hashes -r "$SCRIPTPATH"/requirements.txt

solc-select install $SOLC_VERSION
solc-select use $SOLC_VERSION
export SOLC_VERSION=$SOLC_VERSION


compileContract () {
  local contract
  contract=$(basename "$1" ".sol")

  solc --overwrite --optimize --optimize-runs "$2" --metadata-hash none \
      -o "$ROOT"/contracts/solc/v0.8.19/"$contract" \
      --abi --bin \
      --allow-paths "$ROOT"/../$FOLDER/contracts \
      "$ROOT"/"$1"
}

# OCR2VRF
compileContract ../$FOLDER/contracts/DKG.sol $OPTIMIZE_RUNS
compileContract ../$FOLDER/contracts/VRFBeacon.sol $OPTIMIZE_RUNS
compileContract ../$FOLDER/contracts/VRFCoordinator.sol 1
compileContract ../$FOLDER/contracts/test/TestBeaconVRFConsumer.sol $OPTIMIZE_RUNS
compileContract ../$FOLDER/contracts/test/LoadTestBeaconVRFConsumer.sol $OPTIMIZE_RUNS
