#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │  Compiling legacy Solidity 0.7 contracts...  │"
echo " └──────────────────────────────────────────────┘"

SOLC_VERSION="0.7.6"
OPTIMIZE_RUNS=1000000


SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
ROOT="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../../ && pwd -P )"
python3 -m pip install --require-hashes -r "$SCRIPTPATH"/requirements.txt

solc-select install $SOLC_VERSION
solc-select use $SOLC_VERSION
export SOLC_VERSION=$SOLC_VERSION


compileContract () {
  local contract
  contract=$(basename "$1" ".sol")

  solc --overwrite --optimize --optimize-runs $OPTIMIZE_RUNS --metadata-hash none \
      -o "$ROOT"/contracts/solc/v0.7/"$contract" \
      --abi --bin --allow-paths "$ROOT"/contracts/src/v0.7 \
      "$ROOT"/contracts/src/v0.7/"$1"
}

compileContract tests/MultiWordConsumer.sol
compileContract Operator.sol
compileContract AuthorizedForwarder.sol
compileContract AuthorizedReceiver.sol
compileContract OperatorFactory.sol
compileContract tests/Consumer.sol
compileContract tests/VRFCoordinatorMock.sol

# Keeper/Automation
compileContract KeeperRegistry1_1.sol
compileContract KeeperRegistry1_1Mock.sol
compileContract UpkeepRegistrationRequests.sol
compileContract tests/UpkeepPerformCounterRestrictive.sol
compileContract tests/UpkeepCounter.sol