#!/usr/bin/env bash

set -e

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo $SCRIPTPATH
python3 -m pip install --require-hashes -r $SCRIPTPATH/requirements.txt
solc-select install 0.8.15

# Transmission
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/consumers/Greeter.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/consumers/SCA.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/consumers/SmartContractAccountFactory.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/contracts/EntryPoint.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/utils/SmartContractAccountHelper.sol
