#!/usr/bin/env bash

# This script generates .abi and .bin files for a selected .sol contract.
# Example call:
#   ./contracts/scripts/native_solc_compile dev/Operator.sol
#
# The resulting abi and bin files are stored in ./contracts/solc/v0.8
#
# Ensure that openzepellin libraries are included in node_modules. 
# Run `yarn install --check-files` if they aren't

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd .. && pwd -P )"

solc-select use 0.8.6
solc @openzeppelin/=$SCRIPTPATH/node_modules/@openzeppelin/ --overwrite --optimize --optimize-runs 1000000 --metadata-hash none \
    -o $SCRIPTPATH/solc/v0.8 \
    --abi --bin --allow-paths $SCRIPTPATH/src/v0.8,$SCRIPTPATH/src/v0.8/dev,$SCRIPTPATH/src/v0.8/interfaces,$SCRIPTPATH/src/v0.8/mocks,$SCRIPTPATH/src/v0.8/tests,$SCRIPTPATH/src/v0.8/vendor,$SCRIPTPATH/node_modules/@openzeppelin/ \
    $SCRIPTPATH/src/v0.8/$1