#!/usr/bin/env bash

set -e

echo " ┌──────────────────────────────────────────────┐"
echo " │          Compiling VRF contracts...          │"
echo " └──────────────────────────────────────────────┘"

PROJECT="vrf"
CONTRACTS_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ../ && pwd -P )"

compileContract() {
  local contract=$(basename "$2")
  echo "Compiling" "$contract"

  local optimizer_override=""
  if [[ -n $3 ]]; then
    optimizer_override="--optimizer-runs $3"
  fi

  local command
  command="env FOUNDRY_PROFILE=$1 forge build $CONTRACTS_DIR/src/v0.8/$PROJECT/$2.sol \
   --root $CONTRACTS_DIR \
   --extra-output-files bin abi \
   $optimizer_override \
   -o $CONTRACTS_DIR/solc/$PROJECT/$contract"
  $command
}

# VRF
compileContract vrf VRFRequestIDBase
compileContract vrf VRFConsumerBase
compileContract vrf testhelpers/VRFConsumer
compileContract vrf testhelpers/VRFRequestIDBaseTestHelper
compileContract vrf mocks/VRFCoordinatorMock
#
## VRF V2
compileContract vrf VRFConsumerBaseV2
compileContract vrf testhelpers/ChainSpecificUtilHelper
compileContract vrf testhelpers/VRFConsumerV2
compileContract vrf testhelpers/VRFMaliciousConsumerV2
compileContract vrf testhelpers/VRFTestHelper
compileContract vrf testhelpers/VRFV2RevertingExample
compileContract vrf testhelpers/VRFV2ProxyAdmin
compileContract vrf testhelpers/VRFV2TransparentUpgradeableProxy
compileContract vrf testhelpers/VRFConsumerV2UpgradeableExample
compileContract vrf BatchVRFCoordinatorV2
compileContract vrf testhelpers/VRFCoordinatorV2TestHelper
compileContract vrf VRFCoordinatorV2 10000
compileContract vrf mocks/VRFCoordinatorV2Mock
compileContract vrf VRFOwner
compileContract vrf dev/VRFSubscriptionBalanceMonitor
compileContract vrf KeepersVRFConsumer

# VRF V2 Wrapper
compileContract vrf VRFV2Wrapper
compileContract vrf interfaces/VRFV2WrapperInterface
compileContract vrf VRFV2WrapperConsumerBase
compileContract vrf testhelpers/VRFV2WrapperConsumerExample
compileContract vrf testhelpers/VRFV2WrapperLoadTestConsumer
compileContract vrf testhelpers/VRFv2Consumer

# VRF Consumers and Mocks
compileContract vrf testhelpers/VRFExternalSubOwnerExample
compileContract vrf testhelpers/VRFSingleConsumerExample
compileContract vrf testhelpers/VRFOwnerlessConsumerExample
compileContract vrf testhelpers/VRFLoadTestOwnerlessConsumer
compileContract vrf testhelpers/VRFLoadTestExternalSubOwner
compileContract vrf testhelpers/VRFV2LoadTestWithMetrics
compileContract vrf testhelpers/VRFV2OwnerTestConsumer
compileContract vrf testhelpers/VRFCoordinatorTestV2 10000
compileContract vrf testhelpers/VRFMockETHLINKAggregator
compileContract vrf testhelpers/Counter

# Helper contracts
compileContract vrf interfaces/IAuthorizedReceiver
compileContract vrf interfaces/VRFCoordinatorV2Interface
compileContract vrf interfaces/VRFV2WrapperInterface

# VRF V2 Plus
compileContract vrfv2plus dev/interfaces/IVRFCoordinatorV2PlusInternal
compileContract vrfv2plus dev/testhelpers/VRFV2PlusConsumerExample
compileContract vrfv2plus dev/VRFCoordinatorV2_5 500
compileContract vrfv2plus dev/VRFCoordinatorV2_5_Arbitrum 500
compileContract vrfv2plus dev/VRFCoordinatorV2_5_Optimism 500
compileContract vrfv2plus dev/BatchVRFCoordinatorV2Plus
compileContract vrfv2plus dev/VRFV2PlusWrapper
compileContract vrfv2plus dev/VRFV2PlusWrapper_Arbitrum
compileContract vrfv2plus dev/VRFV2PlusWrapper_Optimism
compileContract vrfv2plus dev/testhelpers/VRFConsumerV2PlusUpgradeableExample
compileContract vrfv2plus dev/testhelpers/VRFMaliciousConsumerV2Plus
compileContract vrfv2plus dev/testhelpers/VRFV2PlusExternalSubOwnerExample
compileContract vrfv2plus dev/testhelpers/VRFV2PlusSingleConsumerExample
compileContract vrfv2plus dev/testhelpers/VRFV2PlusWrapperConsumerExample
compileContract vrfv2plus dev/testhelpers/VRFV2PlusRevertingExample
compileContract vrfv2plus dev/testhelpers/VRFConsumerV2PlusUpgradeableExample
compileContract vrfv2plus dev/testhelpers/VRFV2PlusMaliciousMigrator
compileContract vrfv2plus dev/testhelpers/VRFCoordinatorTestV2_5 500
compileContract vrfv2plus dev/libraries/VRFV2PlusClient
compileContract vrfv2plus dev/testhelpers/VRFCoordinatorV2Plus_V2Example
compileContract vrfv2plus dev/TrustedBlockhashStore
compileContract vrfv2plus dev/testhelpers/VRFV2PlusLoadTestWithMetrics
compileContract vrfv2plus dev/testhelpers/VRFCoordinatorV2PlusUpgradedVersion 5
compileContract vrfv2plus dev/testhelpers/VRFV2PlusWrapperLoadTestConsumer
compileContract vrfv2plus testhelpers/VRFMockETHLINKAggregator
compileContract vrfv2plus dev/testhelpers/VRFV2PlusLoadTestWithMetrics
compileContract vrfv2plus BatchBlockhashStore
compileContract vrfv2plus dev/BlockhashStore
