package filefilter_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/smartcontractkit/chainlink/v2/tools/githooks/internal/filefilter"
)

func TestIsBinary(t *testing.T) {
	t.Parallel()

	t.Run("empty content is not binary", func(t *testing.T) {
		t.Parallel()
		assert.False(t, filefilter.IsBinary([]byte{}))
	})

	t.Run("ascii text is not binary", func(t *testing.T) {
		t.Parallel()
		assert.False(t, filefilter.IsBinary([]byte("package main\n\nfunc main() {}\n")))
	})

	t.Run("utf-8 text is not binary", func(t *testing.T) {
		t.Parallel()
		assert.False(t, filefilter.IsBinary([]byte("Hello, 世界! 🚀\n")))
	})

	t.Run("content with nul byte in first 8KB is binary", func(t *testing.T) {
		t.Parallel()
		data := append([]byte("some header info"), byte(0), 'a', 'b', 'c')
		assert.True(t, filefilter.IsBinary(data))
	})
}

func TestIsEligible(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		path     string
		content  []byte
		expected bool
	}{
		{name: "go file", path: "core/services/app.go", content: []byte("package services"), expected: true},
		{name: "python file", path: "scripts/run.py", content: []byte("import sys"), expected: true},
		{name: "markdown file", path: "README.md", content: []byte("# Title"), expected: true},
		{name: "yaml file", path: "config.yaml", content: []byte("key: value"), expected: true},
		{name: "json file", path: "data.json", content: []byte(`{"a": 1}`), expected: true},
		{name: "toml file", path: "settings.toml", content: []byte("foo = 1"), expected: true},
		{name: "sql file", path: "migrations/0001.sql", content: []byte("SELECT 1;"), expected: true},
		{name: "solidity file", path: "contracts/Token.sol", content: []byte("contract Token {}"), expected: true},
		{name: "dockerfile", path: "Dockerfile", content: []byte("FROM alpine"), expected: true},
		{name: "go mod", path: "go.mod", content: []byte("module foo"), expected: true},
		{name: "png image ignored", path: "assets/logo.png", content: []byte("pngdata"), expected: false},
		{name: "zip archive ignored", path: "dist/bundle.zip", content: []byte("zipdata"), expected: false},
		{name: "wasm binary ignored", path: "plugin.wasm", content: []byte("wasmdata"), expected: false},
		{name: "git directory ignored", path: ".git/HEAD", content: []byte("ref: refs/heads/main"), expected: false},
		{name: "bin directory ignored", path: "tools/githooks/.bin/githooks", content: []byte("bin"), expected: false},
		// Generated operator UI assets (regenerated by make generate); hooks
		// must not "fix" their formatting or they drift from CI output.
		{name: "generated web asset html ignored", path: "core/web/assets/index.html", content: []byte("<!doctype html>"), expected: false},
		{name: "generated web asset js ignored", path: "core/web/assets/main.abc123.js", content: []byte("!function(){}"), expected: false},
		{name: "generated web asset map ignored", path: "core/web/assets/main.abc123.js.map", content: []byte(`{"version":3}`), expected: false},
		{name: "binary content in go file is skipped", path: "corrupt.go", content: []byte("pkg\x00corrupt"), expected: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.expected, filefilter.IsEligible(tt.path, tt.content))
		})
	}
}

func TestIsEligibleFile(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()

	goPath := filepath.Join(tmpDir, "test.go")
	require.NoError(t, os.WriteFile(goPath, []byte("package main\n"), 0o600))

	binPath := filepath.Join(tmpDir, "image.png")
	require.NoError(t, os.WriteFile(binPath, []byte{0x89, 'P', 'N', 'G'}, 0o600))

	eligible, err := filefilter.IsEligibleFile(goPath)
	require.NoError(t, err)
	assert.True(t, eligible)

	eligibleBin, err := filefilter.IsEligibleFile(binPath)
	require.NoError(t, err)
	assert.False(t, eligibleBin)
}
