# See https://github.com/rhysd/actionlint/blob/main/docs/config.md

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # ignore unknown runner labels, as we have fully custom runners
      - 'label ".*" is unknown. available labels are .*'
      # https://www.shellcheck.net/wiki/SC2129
      - '.*SC2129:style:1:1:.*'

