# See https://github.com/rhysd/actionlint/blob/main/docs/config.md

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # ignore unknown runner labels, as we have fully custom runners
      - 'label ".*" is unknown. available labels are .*'
      # https://www.shellcheck.net/wiki/SC2129
      - '.*SC2129:style:.*'
      # https://www.shellcheck.net/wiki/SC2002
      - '.*SC2002:style:.*'
      # ignore if: false, as it's a common pattern to temporarily disable a job or step
      - 'constant expression "false" in condition.*'

