#!/usr/bin/env bash

set -e

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

python3 -m pip install --require-hashes -r $SCRIPTPATH/requirements.txt
solc-select install 0.7.6

$SCRIPTPATH/native_solc7_compile dev/Operator.sol
