name: CI lint for Golang
description: Runs CI lint for Golang
inputs:
  go-directory:
    description: Go directory to run commands from
    default: "."
  # setup-go inputs
  only-modules:
    description: Set to 'true' to only cache modules
    default: "false"
  cache-version:
    description: Set this to cache bust
    default: "1"
  build-cache-version:
    description: For scoping build caches to certain matrix jobs, takes precedence over cache-version
    default: ""
  build-cache-write:
    description: When to save the Go build cache (always, default-branch-only, never)
    default: "always"
  go-version-file:
    description: Set where the go version file is located at
    default: "go.mod"
  go-module-file:
    description: Set where the go module file is located at
    default: "go.sum"

outputs:
  golang-report-artifact-url:
    description: The URL to the uploaded artifact
    value: ${{ steps.upload-artifact.outputs.artifact-url }}
  golang-report-file-count:
    description: The count of files with issues in the uploaded artifact
    value: ${{ steps.print.outputs.file-count }}
  golang-report-issue-count:
    description: The count of issues in the uploaded artifact
    value: ${{ steps.print.outputs.issue-count }}
  golang-report-critical-issue-count:
    description: The count of critical issues in the uploaded artifact
    value: ${{ steps.print.outputs.critical-issue-count }}
  golang-report-per-source-count:
    description: The count of issues per source in the uploaded artifact
    value: ${{ steps.print.outputs.per-source-count }}
  golang-report-per-severity-count:
    description: The count of issues per severity in the uploaded artifact
    value: ${{ steps.print.outputs.per-severity-count }}

runs:
  using: composite
  steps:
    - name: Checkout repo (full)
      uses: actions/checkout@v7
      # Only do a full checkout on merge_groups
      if: github.event_name == 'merge_group'
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Checkout repo
      uses: actions/checkout@v7
      if: github.event_name != 'merge_group'
      with:
        persist-credentials: false
        fetch-depth: 1

    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        only-modules: ${{ inputs.only-modules }}
        cache-version: ${{ inputs.cache-version }}
        build-cache-version: ${{ inputs.build-cache-version }}
        build-cache-write: ${{ inputs.build-cache-write }}
        go-version-file: ${{ inputs.go-version-file }}
        go-module-file: ${{ inputs.go-module-file }}

    - name: Touching core/web/assets/index.html
      shell: bash
      run: mkdir -p core/web/assets && touch core/web/assets/index.html

    - name: Set Golangci-lint working directory
      shell: bash
      id: set-working-directory
      # XXX: Don't use `.` default working directory here due to issues with the golangci-lint-action.
      run: |
        if [ "${{ inputs.go-directory }}" == "." ]; then
          echo "golangci-lint-working-directory=" >> "${GITHUB_OUTPUT}"
        else
          echo "golangci-lint-working-directory=${{ inputs.go-directory }}/" >> "${GITHUB_OUTPUT}"
        fi

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      env:
        # golangci-lint runs with absolute path mode: --path-mode=abs
        REPORT_PATH: ${{ github.workspace }}/${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.xml
        REPORT_PATH_JSON: ${{ github.workspace }}/${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.json
      with:
        version: v2.13.1
        only-new-issues: true
        skip-cache: true
        args: --output.text.path=stdout --output.checkstyle.path=${{ env.REPORT_PATH }} --output.json.path=${{ env.REPORT_PATH_JSON }} --max-same-issues=0 --max-issues-per-linter=0
        working-directory: ${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}

    - name: Print Golangci-lint report results
      id: print
      if: always()
      shell: bash
      env:
        REPORT_PATH_JSON: ./${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.json
        MODULE_NAME: ${{ inputs.go-directory }}
      run: |
        python3 "${{ github.action_path }}/process_report.py"

    - name: Store Golangci-lint report artifact
      if: always()
      id: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        # Use a unique suffix for each lint report artifact to avoid duplication errors
        name: golangci-lint-report-${{ steps.print.outputs.suffix }}
        # N/B: value may be empty (no slash) OR `<path>/<to>/<module>/` (with slash tat the end)
        path: ./${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.*
