// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	synchronization "github.com/smartcontractkit/chainlink/v2/core/services/synchronization"
	mock "github.com/stretchr/testify/mock"
)

// ChipIngressService is an autogenerated mock type for the ChipIngressService type
type ChipIngressService struct {
	mock.Mock
}

type ChipIngressService_Expecter struct {
	mock *mock.Mock
}

func (_m *ChipIngressService) EXPECT() *ChipIngressService_Expecter {
	return &ChipIngressService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *ChipIngressService) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChipIngressService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ChipIngressService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ChipIngressService_Expecter) Close() *ChipIngressService_Close_Call {
	return &ChipIngressService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ChipIngressService_Close_Call) Run(run func()) *ChipIngressService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChipIngressService_Close_Call) Return(_a0 error) *ChipIngressService_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChipIngressService_Close_Call) RunAndReturn(run func() error) *ChipIngressService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// HealthReport provides a mock function with no fields
func (_m *ChipIngressService) HealthReport() map[string]error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthReport")
	}

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func() map[string]error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// ChipIngressService_HealthReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthReport'
type ChipIngressService_HealthReport_Call struct {
	*mock.Call
}

// HealthReport is a helper method to define mock.On call
func (_e *ChipIngressService_Expecter) HealthReport() *ChipIngressService_HealthReport_Call {
	return &ChipIngressService_HealthReport_Call{Call: _e.mock.On("HealthReport")}
}

func (_c *ChipIngressService_HealthReport_Call) Run(run func()) *ChipIngressService_HealthReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChipIngressService_HealthReport_Call) Return(_a0 map[string]error) *ChipIngressService_HealthReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChipIngressService_HealthReport_Call) RunAndReturn(run func() map[string]error) *ChipIngressService_HealthReport_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *ChipIngressService) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ChipIngressService_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ChipIngressService_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ChipIngressService_Expecter) Name() *ChipIngressService_Name_Call {
	return &ChipIngressService_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ChipIngressService_Name_Call) Run(run func()) *ChipIngressService_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChipIngressService_Name_Call) Return(_a0 string) *ChipIngressService_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChipIngressService_Name_Call) RunAndReturn(run func() string) *ChipIngressService_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *ChipIngressService) Ready() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChipIngressService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type ChipIngressService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *ChipIngressService_Expecter) Ready() *ChipIngressService_Ready_Call {
	return &ChipIngressService_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *ChipIngressService_Ready_Call) Run(run func()) *ChipIngressService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChipIngressService_Ready_Call) Return(_a0 error) *ChipIngressService_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChipIngressService_Ready_Call) RunAndReturn(run func() error) *ChipIngressService_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, payload
func (_m *ChipIngressService) Send(ctx context.Context, payload synchronization.TelemPayload) {
	_m.Called(ctx, payload)
}

// ChipIngressService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ChipIngressService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - payload synchronization.TelemPayload
func (_e *ChipIngressService_Expecter) Send(ctx interface{}, payload interface{}) *ChipIngressService_Send_Call {
	return &ChipIngressService_Send_Call{Call: _e.mock.On("Send", ctx, payload)}
}

func (_c *ChipIngressService_Send_Call) Run(run func(ctx context.Context, payload synchronization.TelemPayload)) *ChipIngressService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(synchronization.TelemPayload))
	})
	return _c
}

func (_c *ChipIngressService_Send_Call) Return() *ChipIngressService_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChipIngressService_Send_Call) RunAndReturn(run func(context.Context, synchronization.TelemPayload)) *ChipIngressService_Send_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *ChipIngressService) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChipIngressService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ChipIngressService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ChipIngressService_Expecter) Start(_a0 interface{}) *ChipIngressService_Start_Call {
	return &ChipIngressService_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *ChipIngressService_Start_Call) Run(run func(_a0 context.Context)) *ChipIngressService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ChipIngressService_Start_Call) Return(_a0 error) *ChipIngressService_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChipIngressService_Start_Call) RunAndReturn(run func(context.Context) error) *ChipIngressService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewChipIngressService creates a new instance of ChipIngressService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChipIngressService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChipIngressService {
	mock := &ChipIngressService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
