#!/bin/bash

# Runs a Chainlink node preconfigured to communicate with smartcontract/devnet(parity).
# Steps:
# 0. Have docker installed and configured
# 1. ./devnet/devnet
# 2. cd solidity && truffle migrate --network devnet
# 3. ./cldevnet

export LOG_LEVEL=debug
export ROOT=./devnet
export ETH_URL=ws://localhost:18546
export ETH_CHAIN_ID=17

go run main.go node -d -p "T.tLHkcmwePT/p,]sYuntjwHKAsrhm#4eRs4LuKHwvHejWYAC2JP4M8HimwgmbaZ"
