FROM node:10.16.3 as builder

WORKDIR /app
ADD . .

ARG REACT_APP_INFURA_KEY
ARG REACT_APP_GA_ID
RUN yarn install
RUN yarn workspace @chainlink/feeds run build

FROM node:10.16.3-alpine

WORKDIR /app

COPY --from=builder /app/package.json package.json
COPY --from=builder /app/yarn.lock yarn.lock
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/feeds/node_modules feeds/node_modules
COPY --from=builder /app/feeds/package.json feeds/package.json
COPY --from=builder /app/feeds/server.js feeds/server.js
COPY --from=builder /app/feeds/src feeds/src
COPY --from=builder /app/feeds/public feeds/public
COPY --from=builder /app/feeds/build feeds/build

ENV NODE_ENV production
ENTRYPOINT [ "yarn", "workspace", "@chainlink/feeds", "run", "start" ]
