// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	logger "github.com/smartcontractkit/chainlink/core/logger"

	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: _a0, _a1, _a2
func (_m *Fetcher) Fetch(_a0 context.Context, _a1 map[string]interface{}, _a2 logger.Logger) (decimal.Decimal, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, logger.Logger) decimal.Decimal); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}, logger.Logger) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
