#!/usr/bin/env bash

# Runs tests for a specific product

set -ex

# get this scripts directory
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

cd "$SCRIPT_DIR"/../../ || exit 1

# Arguments needed
# ARGS=${ARGS:=}  any extra args to send to ginkgo
# FOLDER=${FOLDER:=./integration-tests/smoke} # the folder with tests you want to run
# SELECTED_NETWORKS the networks you wish to run against
# CHAINLINK_ENV_USER the user to put in the k8s metadata label
# TEST_LOG_LEVEL the level of logs you wish to have output
echo "TEST_FOLDER=${TEST_FOLDER}"
echo "TEST_ARGS=${TEST_ARGS}"
echo "TEST_SELECTED_NETWORKS=${TEST_SELECTED_NETWORKS}"
# echo "TEST_CHAINLINK_ENV_USER=${TEST_CHAINLINK_ENV_USER}"
# echo "TEST_TEST_LOG_LEVEL=${TEST_TEST_LOG_LEVEL}"
SELECTED_NETWORKS=${TEST_SELECTED_NETWORKS} ginkgo -vv -r --junit-report=tests-smoke-report.xml \
	--keep-going --trace --randomize-all --randomize-suites \
	${TEST_ARGS} \
	${TEST_FOLDER}