#!/usr/bin/env bash

# Runs tests for a specific product

set -ex

# get this scripts directory
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

cd "$SCRIPT_DIR"/../ || exit 1
PRODUCT=${PRODUCT:=cron}
FOCUS=${FOCUS:="@simulated"}
ARGS=${ARGS:=}
ginkgo -v -r --junit-report=tests-smoke-report.xml \
	--keep-going --trace --randomize-all --randomize-suites --progress \
	--focus "$FOCUS" \
	--focus-file "$PRODUCT"_test.go \
	${ARGS} \
	./smoke/