[[automation]]
registryVersion = "2.2"
cl_nodes_funding_eth = 50
# cl_nodes_funding_link = 50
test_keys_min_funding_eth = 10

[automation.MercurySettings]
version = "v2"
credentialsName = "creds0"

[automation.gas_settings]
# EIP1159 fee cap multiplier (default, for all transactions)
fee_cap_multiplier = 2
# EIP1159 fee cap multiplier (default, for all transactions)
tip_cap_multiplier = 2

#[automation.EVMNetworkSettings]
#link_token_address = "0x0165878A594ca255338adfa4d48449f69242Eb8F"
#finality_tag_enabled = true
#finality_depth = 10
#safe_tag_supported = true
#log_poller_interval = '1s'
#[automation.EVMNetworkSettings.head_tracker]
#history_depth = 100
#[automation.EVMNetworkSettings.gas_estimator]
#mode = 'FixedPrice'
#limit_default = 5_000_000

[automation.PublicConfig]
delta_progress=10_000_000_000
delta_resend=15_000_000_000
delta_initial=500_000_000
delta_round=1_000_000_000
delta_grace=200_000_000
delta_certified_commit_request=300_000_000
delta_stage=30_000_000_000
r_max=24
f=1
max_duration_query=20_000_000
max_duration_observation=20_000_000
max_duration_should_accept_attested_report=1_200_000_000
max_duration_should_transmit_accepted_report=20_000_000

[automation.PluginConfig]
perform_lockout_window=3_600_000
target_probability="0.999"
target_in_rounds=1
min_confirmations=0
gas_limit_per_report=10_300_000
gas_overhead_per_upkeep=300_000
max_upkeep_batch_size=10

[automation.PluginConfig.LogProviderConfig]
block_rate=1
log_limit=2

[automation.RegistrySettings]
payment_premium_ppb=200_000_000
flat_fee_micro_link=0
check_gas_limit=2_500_000
staleness_seconds=90000
gas_ceiling_multiplier=1
max_perform_gas=5_000_000
min_upkeep_spend=0
fallback_gas_price=200_000_000_000
fallback_link_price=2_000_000_000_000_000_000
fallback_native_price=2_000_000_000_000_000_000
max_check_data_size=5_000
max_perform_data_size=5_000
max_revert_data_size=5_000