#!/bin/bash

set -ex

# Kill all background processes when this shell script finishes
trap "kill -- -$$ || true" SIGINT SIGTERM EXIT

PATH=./internal/bin:./node_modules/.bin:$PATH

# Utilities
assert ()
{
  echo "$1: expected $2, actual $3."
  if [ "$2" -ne "$3" ]; then
    exit 1
  fi
}

waitForResponse ()
{
  sleepCount=0
  while ! curl -s "$1" && [ "$sleepCount" -le "10" ]; do
      sleep 1
      sleepCount=$((sleepCount+1))
  done

  if [ "$sleepCount" -gt "10" ]; then
    exit 1
  fi
}

# Run gethnet
time go get -d github.com/ethereum/go-ethereum
cd $GOPATH/src/github.com/ethereum/go-ethereum && git checkout v1.8.8 && cd -
time go install github.com/ethereum/go-ethereum/cmd/geth
gethnet &
waitForResponse http://127.0.0.1:18545

# Run CL against ethereum node
cldev &
sleep 4

########################
## Run echo_server sample
########################

cd examples/echo_server
yarn install
truffle migrate
node echo.js &
sleep 1

########################
## runlog
########################

./send_runlog_transaction.js
sleep 2

# Check echo count
count=`curl -sS localhost:6690/count`
assert "Echo count" 1 $count

# Check CL counts
cd ../../

## Check job counts using jq to parse json: https://stedolan.github.io/jq/
jobs=`cldev -j j | jq length`
assert "Jobs count" 1 $jobs

# Check job runs
jid=`cldev -j j | jq 'first | .id' | tr -d '"'`
runs=`cldev -j s $jid |  jq '.runs | length'`
assert "RunLog Runs count" 1 $runs

########################
## ethlog
########################

cd examples/echo_server
ethjob=`./create_ethlog_job`
./send_ethlog_transaction.js
sleep 2

# Check echo count
count=`curl -sS localhost:6690/count`
assert "Echo count" 2 $count

# Check CL counts
cd ../../

## Check job counts
jobs=`cldev -j j | jq length`
assert "Jobs count" 2 $jobs

## Check job runs
jid=`echo $ethjob | jq .id | tr -d '"'`
runs=`cldev -j s $jid |  jq '.runs | length'`
assert "EthLog Runs count" 1 $runs
