#!/bin/bash

set -e

packages=`go list -f '{{.ImportPath}},' ./... | grep -v "internal\|gui\|tmp" \
  | tr -d '\n' | sed 's/,$//'`

cc-test-reporter before-build
go test -v -parallel 2 --tags=test -coverprofile=c.out -coverpkg=$packages ./...
result=$?
if [ -n "$CC_TEST_REPORTER_ID"  ]; then
  cc-test-reporter after-build -t gocov --exit-code $result
fi
bash <(curl -s https://codecov.io/bash)
