#!/bin/bash

set -e

cd gui
yarn lint-ci && yarn test-ci

cd ..
cc-test-reporter format-coverage --output "coverage/codeclimate.gui.json"
gsutil cp "coverage/codeclimate.gui.json" gs://chainlink-test-coverage/$CIRCLE_WORKFLOW_ID/
