#!/bin/bash

set -e

yarn tslint && yarn lint-ci

cd gui
yarn install && yarn test-ci

if [ -n "$CC_TEST_REPORTER_ID"  ]; then
  cc-test-reporter format-coverage --output "coverage/codeclimate.gui.json"
  gsutil cp "coverage/codeclimate.gui.json" gs://chainlink-test-coverage/$CIRCLE_WORKFLOW_ID/
fi
