#!/bin/bash

# Dep
curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
chmod +x $GOPATH/bin/dep

# Goverage
go get -u github.com/smartcontractkit/goverage

# Yarn
sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update -qq
sudo apt-get install -y -qq yarn

# Code Climate
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $GOPATH/bin/cc-test-reporter
chmod +x $GOPATH/bin/cc-test-reporter

dep ensure
yarn install
