#!/bin/bash -e

set -x

export ENVIRONMENT=${ENVIRONMENT:-release}

tmpdir=$(mktemp -d)
trap "rm -rf $tmpdir" EXIT HUP TERM INT
libs="$PWD/sgx/target/$ENVIRONMENT"
cp ./sgx/target/$ENVIRONMENT/enclave.signed.so $tmpdir/
go test -tags=sgx_enclave -ldflags "-r $libs" ./adapters/ -c -o "$tmpdir/adapters.test"
cd $tmpdir
./adapters.test -test.parallel 1 -test.v
