#!/bin/bash

set -e

yarn solium --dir solidity/
yarn solium --dir examples/

cd solidity
../node_modules/.bin/truffle test --network test

cd ../examples/uptime_sla
yarn install
./node_modules/.bin/truffle test --network test

cd ../echo_server
yarn install
./node_modules/.bin/truffle test --network test
