set fallback

# Default: show available recipes
default:
    just --list

clean:
    rm -rf compose/ blockscout/

build-fakes registry platform="linux/amd64":
    just fakes/build {{registry}}

push-fakes registry:
    just fakes/push {{registry}}

# Rebuild CLI
cli:
    pushd cmd/cl > /dev/null && go install -ldflags="-X main.Version=1.0.0" . && popd > /dev/null