name: Setup CI Core Tests
description: |
  Shared setup steps for ci-core.
  Note: Other actions should not be called from this action. There is
  weird behavior when nesting reusable actions.
inputs:

  go-mod-download-directory:
    description: |
      The directory to run go mod download in. If not provided, it will not run go mod download.
    required: false
    default: ""

  db-url:
    description: |
      The expected database URL
    required: true

runs:
  using: composite
  steps:
    - name: Touching core/web/assets/index.html
      shell: bash
      run: mkdir -p core/web/assets && touch core/web/assets/index.html

    - name: Download Go vendor packages
      shell: bash
      run: go mod download

    - name: Go Mod Download (optional)
      if: ${{ inputs.go-mod-download-directory != '' }}
      shell: bash
      working-directory: ${{ inputs.go-mod-download-directory }}
      run: go mod download

    - name: Set go Cache Key Inputs
      shell: bash
      id: go-cache-inputs
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      run: |
        echo "gobuildcache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "branchname=${BRANCH_NAME}" >> $GITHUB_OUTPUT

    - uses: actions/cache/restore@v4
      name: Restore go build cache for initial test binary
      id: cache-restore
      with:
        path: |
          ${{ steps.go-cache-inputs.outputs.gobuildcache }}
        key: ${{ runner.os }}-gobuild-core-test-binary-${{ hashFiles('./go.mod') }}-${{ steps.go-cache-inputs.outputs.branchname }}
        restore-keys: |
          ${{ runner.os }}-gomod--core-test-binary-

    - name: Build binary
      shell: bash
      run: go build -o chainlink.test .

    - uses: actions/cache/save@v4
      name: Save go build cache for initial test binary
      with:
        path: |
          ${{ steps.go-cache-inputs.outputs.gobuildcache }}
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}

    - name: Setup DB
      shell: bash
      run: ./chainlink.test local db preparetest
      env:
        CL_DATABASE_URL: ${{ inputs.db-url }}

    - name: Install LOOP Plugins
      shell: bash
      run: |
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-feeds)
        go install ./cmd/chainlink-feeds
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-data-streams)
        go install ./mercury/cmd/chainlink-mercury
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-solana)
        go install ./pkg/solana/cmd/chainlink-solana
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-starknet/relayer)
        go install ./pkg/chainlink/cmd/chainlink-starknet
        popd

