[[products]]
name = "flux"
instances = 1

[[nodesets]]
  name = "don"
  nodes = 3
  override_mode = "each"

  [nodesets.db]
    image = "postgres:15.0"

  [[nodesets.node_specs]]
    [nodesets.node_specs.node]
        image = "public.ecr.aws/chainlink/chainlink:2.30.0"

  [[nodesets.node_specs]]
    [nodesets.node_specs.node]
        image = "public.ecr.aws/chainlink/chainlink:2.30.0"

  [[nodesets.node_specs]]
    [nodesets.node_specs.node]
        image = "public.ecr.aws/chainlink/chainlink:2.30.0"


[[flux]]
    [flux.gas_settings]
    fee_cap_multiplier = 2
    tip_cap_multiplier = 2
