name: Solana build contracts
description: Build Solana contracts

runs:
  using: composite
  steps:
    - name: Build Solana contracts
      id: build_solana_contracts
      shell: bash
      run: ./deployment/ccip/changeset/internal/build_solana_contracts.sh
