name: Solana build contracts
description: Build Solana contracts
inputs:
  github-token:
    description: "The Github token to use for authentication"
    required: true
    default: ${{ github.token }}

# TODO: for debugging purposes only - this should be restored to its original contents later
runs:
  using: composite
  steps:
    - name: Download Release Artifacts
      shell: bash
      run: |
        short_revision=$(grep "github.com/smartcontractkit/chainlink-ccip/chains/solana" deployment/go.mod | awk '{print $2}' | cut -d'-' -f3)
        curl -L -o artifacts.tar.gz "https://github.com/smartcontractkit/chainlink-ccip/releases/download/solana-artifacts-localtest-$short_revision/artifacts.tar.gz"
        tar -xzvf artifacts.tar.gz
        mkdir -p /home/runner/work/chainlink/chainlink/deployment/ccip/changeset/internal/solana_contracts
        cp target/deploy/*.so /home/runner/work/chainlink/chainlink/deployment/ccip/changeset/internal/solana_contracts
