name: Setup Solana CLI
description: Setup solana CLI
inputs:
  version:
    description: Solana release version
    required: false
    default: "v1.18.26"
  shasum:
    description: SHA256 checksum of install script
    required: false
    default: "cec72cde1cf36eb35cd8326245d23af0b6791fab68337c2953e2ca2a40af2c50"

runs:
  using: composite
  steps:
    - uses: actions/cache@v6
      id: cache
      name: Cache solana CLI
      with:
        path: |
          ~/.local/share/solana
        key: ${{ runner.os }}-${{ runner.arch }}-solana-cli-${{ inputs.version }}-${{ inputs.shasum }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-solana-cli-

    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Install solana cli
      shell: bash
      run: |
        set -euo pipefail
        curl -sSfL "https://release.anza.xyz/${{ inputs.version }}/install" --output install_solana.sh
        echo "${{ inputs.shasum }}  install_solana.sh" | sha256sum --check
        chmod +x install_solana.sh
        sh -c ./install_solana.sh
        rm -f install_solana.sh

    - name: Export solana path to env
      shell: bash
      run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> "${GITHUB_ENV}"
