# billing service
[billing_platform_service]
  compose_file='https://raw.githubusercontent.com/smartcontractkit/chainlink-testing-framework/8d154e9c1529bb9a1a719956c131604aa8f05b98/framework/components/dockercompose/billing_platform_service/docker-compose.yml'