export const CLEAR_STATE = 'aggregation/CLEAR_STATE'
export const OPTIONS = 'aggregation/OPTIONS'
export const CONTRACT_ADDRESS = 'aggregation/CONTRACT_ADDRESS'
export const ORACLES = 'aggregation/ORACLES'
export const CURRENT_ANSWER = 'aggregation/CURRENT_ANSWER'
export const LATEST_COMPLETED_ANSWER_ID =
  'aggregation/LATEST_COMPLETED_ANSWER_ID'
export const PENDING_ANSWER_ID = 'aggregation/PENDING_ANSWER_ID'
export const NEXT_ANSWER_ID = 'aggregation/NEXT_ANSWER_ID'
export const ORACLE_RESPONSE = 'aggregation/ORACLE_RESPONSE'
export const REQUEST_TIME = 'aggregation/REQUEST_TIME'
export const MINUMUM_RESPONSES = 'aggregation/MINUMUM_RESPONSES'
export const UPDATE_HEIGHT = 'aggregation/UPDATE_HEIGHT'
export const ANSWER_HISTORY = 'aggregation/ANSWER_HISTORY'
