// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

enum FulfillResult {
  USER_SUCCESS, // 0
  USER_ERROR, // 1
  INVALID_REQUEST_ID, // 2
  COST_EXCEEDS_COMMITMENT, // 3
  INSUFFICIENT_GAS_PROVIDED, // 4
  SUBSCRIPTION_BALANCE_INVARIANT_VIOLATION, // 5
  INVALID_COMMITMENT // 6
}
