package plugins

import (
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/smartcontractkit/chainlink-relay/pkg/loop"
)

// RegistrarConfig generates contains static configuration inher
type RegistrarConfig interface {
	RegisterLOOP(loopId string, cmdName string) (func() *exec.Cmd, loop.GRPCOpts, error)
}

type registarConfig struct {
	grpcOpts           loop.GRPCOpts
	loopRegistrationFn func(loopId string) (*RegisteredLoop, error)
}

// NewRegistrarConfig creates a RegistarConfig
// loopRegistrationFn must act as a global registry function of LOOPs and must be idempotent.
// The [func() *exec.Cmd] for a LOOP should be generated by calling [RegistrarConfig.RegisterLOOP]
func NewRegistrarConfig(grpcOpts loop.GRPCOpts, loopRegistrationFn func(loopId string) (*RegisteredLoop, error)) RegistrarConfig {
	return &registarConfig{
		grpcOpts:           grpcOpts,
		loopRegistrationFn: loopRegistrationFn,
	}
}

// RegisterLOOP calls the configured loopRegistrationFn. The loopRegistrationFn must act as a global registry for LOOPs and must be idempotent.
func (pc *registarConfig) RegisterLOOP(loopID string, cmdName string) (func() *exec.Cmd, loop.GRPCOpts, error) {
	cmdFn, err := NewCmdFactory(pc.loopRegistrationFn, CmdConfig{
		ID:  loopID,
		Cmd: cmdName,
	})
	if err != nil {
		return nil, loop.GRPCOpts{}, err
	}
	return cmdFn, pc.grpcOpts, nil
}

// EnvConfig is the configuration interface between the application and the LOOP executable.
// The values are fully resolved and static and passed via the environment.
type EnvConfig interface {
	PrometheusPort() int

	// Enables trace generation and collection on the plugin
	TracingEnabled() bool

	// The logical address of the trace collector
	TracingCollectorTarget() string

	// Attributes to be added to the node's tracing context
	TracingAttributes() map[string]string

	// The sampling ratio for the node's tracing context
	TracingSamplingRatio() float64
}

// SetCmdEnvFromConfig sets LOOP-specific vars in the env of the given cmd.
// It also, due to the plugin library, forwards all env vars from the host automatically.
// TODO: BCF-2662: Remove once we can use skipHostEnv in hashicorp/go-plugin v1.5.0
// This method is consumed by the host.
func SetCmdEnvFromConfig(cmd *exec.Cmd, cfg EnvConfig) {
	injectEnv := map[string]string{
		"CL_PROMETHEUS_PORT":       strconv.Itoa(cfg.PrometheusPort()),
		"TRACING_ENABLED":          strconv.FormatBool(cfg.TracingEnabled()),
		"TRACING_COLLECTOR_TARGET": cfg.TracingCollectorTarget(),
		"TRACING_SAMPLING_RATIO":   strconv.FormatFloat(cfg.TracingSamplingRatio(), 'f', -1, 64),
	}

	for k, v := range cfg.TracingAttributes() {
		injectEnv["TRACING_ATTRIBUTE_"+k] = v
	}

	for k, v := range injectEnv {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
}

// isTracingEnabled parses and validates the TRACING_ENABLED environment variable.
func getTracingEnabled() (bool, error) {
	tracingEnabledString := os.Getenv("TRACING_ENABLED")
	if tracingEnabledString == "" {
		return false, nil
	}
	return strconv.ParseBool(tracingEnabledString)
}

// getValidCollectorTarget validates TRACING_COLLECTOR_TARGET as a URL.
func getValidCollectorTarget() (string, error) {
	tracingCollectorTarget := os.Getenv("TRACING_COLLECTOR_TARGET")
	_, err := url.ParseRequestURI(tracingCollectorTarget)
	if err != nil {
		return "", fmt.Errorf("invalid TRACING_COLLECTOR_TARGET: %w", err)
	}
	return tracingCollectorTarget, nil
}

// getTracingAttributes collects attributes prefixed with TRACING_ATTRIBUTE_.
func getTracingAttributes() map[string]string {
	tracingAttributes := make(map[string]string)
	for _, env := range os.Environ() {
		if strings.HasPrefix(env, "TRACING_ATTRIBUTE_") {
			tracingAttributes[strings.TrimPrefix(env, "TRACING_ATTRIBUTE_")] = os.Getenv(env)
		}
	}
	return tracingAttributes
}

// getTracingSamplingRatio parses the TRACING_SAMPLING_RATIO environment variable.
// Any errors in parsing result in a sampling ratio of 0.0.
func getTracingSamplingRatio() float64 {
	tracingSamplingRatio := os.Getenv("TRACING_SAMPLING_RATIO")
	if tracingSamplingRatio == "" {
		return 0.0
	}
	samplingRatio, err := strconv.ParseFloat(tracingSamplingRatio, 64)
	if err != nil {
		return 0.0
	}
	return samplingRatio
}

// GetEnvConfig deserializes LOOP-specific environment variables to an EnvConfig.
func GetEnvConfig() (EnvConfig, error) {
	promPortStr := os.Getenv("CL_PROMETHEUS_PORT")
	promPort, err := strconv.Atoi(promPortStr)
	if err != nil {
		return nil, fmt.Errorf("failed to parse CL_PROMETHEUS_PORT: %w", err)
	}

	tracingEnabled, err := getTracingEnabled()
	if err != nil {
		return nil, fmt.Errorf("failed to parse TRACING_ENABLED: %w", err)
	}

	var tracingCollectorTarget string
	var tracingAttributes map[string]string
	var tracingSamplingRatio float64
	if tracingEnabled {
		tracingCollectorTarget, err = getValidCollectorTarget()
		if err != nil {
			return nil, err
		}
		tracingAttributes = getTracingAttributes()
		tracingSamplingRatio = getTracingSamplingRatio()
	}

	return &envConfig{
		prometheusPort:         promPort,
		tracingEnabled:         tracingEnabled,
		tracingCollectorTarget: tracingCollectorTarget,
		tracingAttributes:      tracingAttributes,
		tracingSamplingRatio:	tracingSamplingRatio,
	}, nil
}

// envConfig is an implementation of EnvConfig.
type envConfig struct {
	prometheusPort         int
	tracingEnabled         bool
	tracingCollectorTarget string
	tracingAttributes      map[string]string
	tracingSamplingRatio   float64
}

func (e *envConfig) PrometheusPort() int {
	return e.prometheusPort
}

func (e *envConfig) TracingEnabled() bool {
	return e.tracingEnabled
}

func (e *envConfig) TracingCollectorTarget() string {
	return e.tracingCollectorTarget
}

func (e *envConfig) TracingAttributes() map[string]string {
	return e.tracingAttributes
}

func (e *envConfig) TracingSamplingRatio() float64 {
	return e.tracingSamplingRatio
}
