[CCIP]
[CCIP.ContractVersions]
PriceRegistry = 'latest'
OffRamp = 'latest'
OnRamp = 'latest'
CommitStore = 'latest'
TokenPool = '1.4.0'

[CCIP.Groups.smoke.TokenConfig]
CCIPOwnerTokens = true

[CCIP.Groups.load.TokenConfig]
CCIPOwnerTokens = true