ChainID = '61166'
ChainType = 'zksync'
LogPollInterval = '10s'
NoNewHeadsThreshold = '5m' #blocks production can sometimes be delayed by ~5min

[GasEstimator.DAOracle]
OracleType = 'zksync'

[HeadTracker]
HistoryDepth = 250
