// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: events-workflow-finished.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowExecutionFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M             *WorkflowMetadata      `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionFinished) Reset() {
	*x = WorkflowExecutionFinished{}
	mi := &file_events_workflow_finished_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionFinished) ProtoMessage() {}

func (x *WorkflowExecutionFinished) ProtoReflect() protoreflect.Message {
	mi := &file_events_workflow_finished_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionFinished.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionFinished) Descriptor() ([]byte, []int) {
	return file_events_workflow_finished_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowExecutionFinished) GetM() *WorkflowMetadata {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *WorkflowExecutionFinished) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WorkflowExecutionFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_events_workflow_finished_proto protoreflect.FileDescriptor

const file_events_workflow_finished_proto_rawDesc = "" +
	"\n" +
	"\x1eevents-workflow-finished.proto\x12\x02pb\x1a\x15events-metadata.proto\"u\n" +
	"\x19WorkflowExecutionFinished\x12\"\n" +
	"\x01m\x18\x01 \x01(\v2\x14.pb.WorkflowMetadataR\x01m\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusBCZAgithub.com/smartcontractkit/chainlink/core/services/workflows/pb/b\x06proto3"

var (
	file_events_workflow_finished_proto_rawDescOnce sync.Once
	file_events_workflow_finished_proto_rawDescData []byte
)

func file_events_workflow_finished_proto_rawDescGZIP() []byte {
	file_events_workflow_finished_proto_rawDescOnce.Do(func() {
		file_events_workflow_finished_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_workflow_finished_proto_rawDesc), len(file_events_workflow_finished_proto_rawDesc)))
	})
	return file_events_workflow_finished_proto_rawDescData
}

var file_events_workflow_finished_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_workflow_finished_proto_goTypes = []any{
	(*WorkflowExecutionFinished)(nil), // 0: pb.WorkflowExecutionFinished
	(*WorkflowMetadata)(nil),          // 1: pb.WorkflowMetadata
}
var file_events_workflow_finished_proto_depIdxs = []int32{
	1, // 0: pb.WorkflowExecutionFinished.m:type_name -> pb.WorkflowMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_workflow_finished_proto_init() }
func file_events_workflow_finished_proto_init() {
	if File_events_workflow_finished_proto != nil {
		return
	}
	file_events_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_workflow_finished_proto_rawDesc), len(file_events_workflow_finished_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_workflow_finished_proto_goTypes,
		DependencyIndexes: file_events_workflow_finished_proto_depIdxs,
		MessageInfos:      file_events_workflow_finished_proto_msgTypes,
	}.Build()
	File_events_workflow_finished_proto = out.File
	file_events_workflow_finished_proto_goTypes = nil
	file_events_workflow_finished_proto_depIdxs = nil
}
