syntax = "proto3";

option go_package = "github.com/smartcontractkit/chainlink/core/services/workflows/pb/";

package pb;

// an example of how the protos in events could be structured differently.
// due to the difficulty of oneof processing in the events pipeline,
// we should not proceed with this approach.
message WorkflowEvent2 {
  // Common metadata shared by all events.
  WorkflowMetadata2 metadata = 1;

  // A 'oneof' to carry whichever event-specific payload we have.
  oneof event_type {
    WorkflowExecutionStarted2 workflow_execution_started = 2;
    WorkflowExecutionFinished2 workflow_execution_finished = 3;
    CapabilityExecutionStarted2 capability_execution_started = 4;
    CapabilityExecutionFinished2 capability_execution_finished = 5;
  }
}

message WorkflowMetadata2 {
  string workflowName = 1;
  string version = 2;
  string workflowID = 3;
  string workflowExecutionID = 4;
  string donID = 5;
  int32 donF = 6;
  int32 donN = 7;
  int32 donQ = 8;
  string p2pID = 9;
}

message WorkflowExecutionStarted2 {
  string timestamp = 2;
  string TriggerID = 3;
}

message WorkflowExecutionFinished2 {
  string timestamp = 2;
  string status = 3;
}

message CapabilityExecutionStarted2 {
  string timestamp = 2;
  string capabilityID = 3;
  string stepRef = 4;
}

message CapabilityExecutionFinished2 {
  string timestamp = 2;
  string capabilityID = 3;
  string stepRef = 4;
  string status = 5;
}