preview-staging:
	iron-flask deploy-schemas -e staging -c ./iron_flask.yaml --preview

deploy-staging:
	iron-flask deploy-schemas -e staging -c ./iron_flask.yaml

destroy-staging:
	iron-flask deploy-schemas -e staging -c ./iron_flask.yaml --destroy

preview-prod:
	iron-flask deploy-schemas -e prod -c ./iron_flask.yaml --preview

deploy-prod:
	iron-flask deploy-schemas -e prod -c ./iron_flask.yaml

destroy-prod:
	iron-flask deploy-schemas -e prod -c ./iron_flask.yaml --destroy
