// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: chip_load_test_demo.proto

package beholder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used for testing
type DemoClientPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Entity        string                 `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	BatchNum      int64                  `protobuf:"varint,4,opt,name=batch_num,json=batchNum,proto3" json:"batch_num,omitempty"`
	MessageNum    int64                  `protobuf:"varint,5,opt,name=message_num,json=messageNum,proto3" json:"message_num,omitempty"`
	BatchPosition int64                  `protobuf:"varint,6,opt,name=batch_position,json=batchPosition,proto3" json:"batch_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoClientPayload) Reset() {
	*x = DemoClientPayload{}
	mi := &file_chip_load_test_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoClientPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoClientPayload) ProtoMessage() {}

func (x *DemoClientPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chip_load_test_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoClientPayload.ProtoReflect.Descriptor instead.
func (*DemoClientPayload) Descriptor() ([]byte, []int) {
	return file_chip_load_test_demo_proto_rawDescGZIP(), []int{0}
}

func (x *DemoClientPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DemoClientPayload) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DemoClientPayload) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *DemoClientPayload) GetBatchNum() int64 {
	if x != nil {
		return x.BatchNum
	}
	return 0
}

func (x *DemoClientPayload) GetMessageNum() int64 {
	if x != nil {
		return x.MessageNum
	}
	return 0
}

func (x *DemoClientPayload) GetBatchPosition() int64 {
	if x != nil {
		return x.BatchPosition
	}
	return 0
}

var File_chip_load_test_demo_proto protoreflect.FileDescriptor

const file_chip_load_test_demo_proto_rawDesc = "" +
	"\n" +
	"\x19chip_load_test_demo.proto\x12\x02pb\"\xb8\x01\n" +
	"\x11DemoClientPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06entity\x18\x03 \x01(\tR\x06entity\x12\x1b\n" +
	"\tbatch_num\x18\x04 \x01(\x03R\bbatchNum\x12\x1f\n" +
	"\vmessage_num\x18\x05 \x01(\x03R\n" +
	"messageNum\x12%\n" +
	"\x0ebatch_position\x18\x06 \x01(\x03R\rbatchPositionBJZHgithub.com/smartcontractkit/chainlink/v2/core/services/beholder;beholderb\x06proto3"

var (
	file_chip_load_test_demo_proto_rawDescOnce sync.Once
	file_chip_load_test_demo_proto_rawDescData []byte
)

func file_chip_load_test_demo_proto_rawDescGZIP() []byte {
	file_chip_load_test_demo_proto_rawDescOnce.Do(func() {
		file_chip_load_test_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chip_load_test_demo_proto_rawDesc), len(file_chip_load_test_demo_proto_rawDesc)))
	})
	return file_chip_load_test_demo_proto_rawDescData
}

var file_chip_load_test_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chip_load_test_demo_proto_goTypes = []any{
	(*DemoClientPayload)(nil), // 0: pb.DemoClientPayload
}
var file_chip_load_test_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chip_load_test_demo_proto_init() }
func file_chip_load_test_demo_proto_init() {
	if File_chip_load_test_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chip_load_test_demo_proto_rawDesc), len(file_chip_load_test_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chip_load_test_demo_proto_goTypes,
		DependencyIndexes: file_chip_load_test_demo_proto_depIdxs,
		MessageInfos:      file_chip_load_test_demo_proto_msgTypes,
	}.Build()
	File_chip_load_test_demo_proto = out.File
	file_chip_load_test_demo_proto_goTypes = nil
	file_chip_load_test_demo_proto_depIdxs = nil
}
