#!/usr/bin/env bash

set -e

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; cd ..; pwd -P )"
echo $SCRIPTPATH
python3 -m pip install --require-hashes -r $SCRIPTPATH/requirements.txt
solc-select install 0.8.15

# Contracts
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/contracts/SCA.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/contracts/Paymaster.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/contracts/SmartContractAccountFactory.sol

# Testhelpers
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/testhelpers/SmartContractAccountHelper.sol
$SCRIPTPATH/native_solc8_15_compile dev/transmission/entrypoint_implementation/testhelpers/Greeter.sol

# Vendor
$SCRIPTPATH/native_solc8_15_compile dev/vendor/entrypoint/core/EntryPoint.sol
