name: Setup Aptos CLI
description: Setup Aptos CLI
runs:
  using: composite
  steps:
    - name: Install Aptos CLI
      uses: aptos-labs/actions/install-aptos-cli@ce57287eb852b9819c1d74fecc3be187677559fd # v0.1
      with:
        CLI_VERSION: 7.2.0