name: Setup Aptos CLI
description: Install and cache Aptos CLI
inputs:
  version:
    description: Aptos CLI version
    required: false
    default: "8.1.0"

runs:
  using: composite
  steps:
    - name: Cache Aptos CLI
      id: cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.local/bin/aptos
        key: ${{ runner.os }}-${{ runner.arch }}-aptos-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-aptos-

    - name: Install Aptos CLI
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      uses: aptos-labs/actions/install-aptos-cli@70f94109f7392b0ca0ae156fdee567b4bb6a52f6 # 2026-04-07
      with:
        CLI_VERSION: ${{ inputs.version }}

    - name: Export Aptos CLI to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
