#!/usr/bin/env bash
set -x
set -euo pipefail

ENABLE_GORELEASER_SNAPSHOT=${ENABLE_GORELEASER_SNAPSHOT:-false}
ENABLE_GORELEASER_SPLIT=${ENABLE_GORELEASER_SPLIT:-false}
GORELEASER_CONFIG=${GORELEASER_CONFIG:-.goreleaser.yaml}

# wrapper function to invoke goreleaser release
goreleaser_release() {
  goreleaser_flags=()

  # set goreleaser flags
  if [[ $ENABLE_GORELEASER_SNAPSHOT == "true" ]]; then
    goreleaser_flags+=("--snapshot")
    goreleaser_flags+=("--clean")
  fi

  if [[ $ENABLE_GORELEASER_SPLIT == "true" ]]; then
    goreleaser_flags+=("--split")
  fi

  if [[ $ENABLE_GORELEASER_NIGHTLY == "true" ]]; then
    goreleaser_flags+=("--nightly")
  fi

  flags=$(printf "%s " "${goreleaser_flags[@]}")
  flags=$(echo "$flags" | sed 's/ *$//')

  export CHAINLINK_VERSION=$(jq -r '.version' package.json) 
  
  goreleaser release ${flags} --config "$GORELEASER_CONFIG" "$@"

}

"$@"
