#!/usr/bin/env bash

set -e

# src/v0.8/ccip/libraries/Internal.sol
# src/v0.8/ccip/libraries/RateLimiter.sol
# src/v0.8/ccip/libraries/USDPriceWith18Decimals.sol
# src/v0.8/ccip/libraries/MerkleMultiProof.sol
# excluded because Foundry doesn't support coverage on library files


lcov --remove $1 -o $2 \
  '*/ccip/test/*' \
  '*/vendor/*' \
  '*/shared/*' \
  'src/v0.8/ccip/ocr/OCR2Abstract.sol' \
  'src/v0.8/ccip/libraries/Internal.sol' \
  'src/v0.8/ccip/libraries/RateLimiter.sol' \
  'src/v0.8/ccip/libraries/USDPriceWith18Decimals.sol' \
  'src/v0.8/ccip/libraries/MerkleMultiProof.sol' \
  'src/v0.8/ConfirmedOwnerWithProposal.sol' \
  'src/v0.8/tests/MockV3Aggregator.sol' \
  'src/v0.8/ccip/applications/CCIPClientExample.sol' \
  --rc lcov_branch_coverage=1
