#!/bin/bash

set -e

GIT_ROOT=`git rev-parse --show-toplevel`

export SRCROOT=${CIRCLE_WORKING_DIRECTORY:-${TRAVIS_BUILD_DIR:-$GIT_ROOT}}
export PATH=$SRCROOT/tools/bin:./node_modules/.bin:$PATH

export ROOT="$SRCROOT/tools/clroot"

export ECHO_SERVER_PORT=6690
export ECHO_SERVER_URL=http://127.0.0.1:$ECHO_SERVER_PORT/count

export CHAINLINK_PORT=6688
export CHAINLINK_URL=http://127.0.0.1:$CHAINLINK_PORT/

pushd $SRCROOT >/dev/null

source ./integration/common
source ./tools/bin/clenv

trap cleanup EXIT SIGTERM SIGINT
trap exit_handler EXIT

heading 'Setup...'

if [ "$1" == "parity" ]; then
  launch_parity
else
  launch_gethnet
fi

launch_chainlink
deploy_oracle_and_linktoken_contracts
launch_echo_server
chainlink login --file ./tools/clroot/apicredentials

heading 'Running tests...'

pushd integration >/dev/null

./runlog_test
./ethlog_test

title 'End to end tests.'

set -o pipefail
yarn cross-env NODE_ENV=test yarn jest e2e/ --runInBand | tee e2e.tests.log
set +o pipefail

title 'All tests passed.'

# Return to caller's PWD
popd >/dev/null
popd >/dev/null
