#!/bin/bash

set -e

GIT_ROOT=`git rev-parse --show-toplevel`

export SRCROOT=`pwd`
export PATH=$SRCROOT/tools/bin:./node_modules/.bin:$PATH

export ROOT="$SRCROOT/tools/clroot"

export ECHO_SERVER_PORT=6690
export ECHO_SERVER_URL=http://127.0.0.1:$ECHO_SERVER_PORT/count

export CHAINLINK_PORT=6688
export CHAINLINK_URL=http://127.0.0.1:$CHAINLINK_PORT/

export MIN_OUTGOING_CONFIRMATIONS=1
export MIN_INCOMING_CONFIRMATIONS=1

pushd $SRCROOT >/dev/null

source ./integration/common
source ./tools/bin/clenv

trap cleanup EXIT SIGTERM SIGINT
trap exit_handler EXIT

heading 'Setup...'

if [ "$1" == "parity" ]; then
  export ETH_CHAIN_ID=34055
  launch_parity
else
  export ETH_CHAIN_ID=1337
  launch_gethnet
fi

launch_explorer
add_clnode_to_explorer
launch_chainlink
deploy_contracts
launch_echo_server
chainlink login --file ./tools/clroot/apicredentials

heading 'Running tests...'

pushd integration >/dev/null

./runlog_test
./ethlog_test

title 'End to end tests.'

set -o pipefail
yarn workspace @chainlink/integration run test | tee $SRCROOT/integration/e2e.tests.log
set +o pipefail

title 'All tests passed.'

# Return to caller's PWD
popd >/dev/null
