#!/bin/bash

set -e

# Generate contract artifacts
yarn install --ignore-engines

yarn setup:contracts

# Run golang coverage
go get -u github.com/smartcontractkit/goverage
goverage -v -parallel 2 ./...
