#!/bin/bash

set -e

yarn lint:styleguide && yarn lint:operator_ui

cd operator_ui
../node_modules/.bin/cross-env NODE_ENV=test \
  ../node_modules/.bin/jest --runInBand --coverage --reporters jest-silent-reporter

if [ -n "$CC_TEST_REPORTER_ID"  ]; then
  cc-test-reporter format-coverage --output "coverage/codeclimate.operator_ui.json"
  gsutil cp "coverage/codeclimate.operator_ui.json" gs://chainlink-test-coverage/$CIRCLE_WORKFLOW_ID/
fi
