#!/usr/bin/env bash

set -euo pipefail

# latest release tag
GIT_TAG="v0.61.10"

CHECKOUT_DIR="${HOME}/wasmd-checkout"
BUILD_DIR="${HOME}/wasmd-build"

git clone https://github.com/CosmWasm/wasmd --branch "${GIT_TAG}" "${CHECKOUT_DIR}"
cd "${CHECKOUT_DIR}"
git checkout "${GIT_TAG}"
GOTOOLCHAIN=go1.25.8 GOPATH="${BUILD_DIR}" make install
