#!/usr/bin/env bash

set -euo pipefail

# commit on branch releases/v0.3x
CHECKOUT_SHA1="d48bb69b391edf92228708008dcd5bbe47b83128"

CHECKOUT_DIR="${HOME}/wasmd-checkout"
BUILD_DIR="${HOME}/wasmd-build"

git clone https://github.com/CosmWasm/wasmd --branch "releases/v0.3x" "${CHECKOUT_DIR}"
cd "${CHECKOUT_DIR}"
git reset --hard "${CHECKOUT_SHA1}"
GOPATH="${BUILD_DIR}" make install
