#!/bin/bash

set -e

GIT_ROOT=`git rev-parse --show-toplevel`

export SRCROOT=`pwd`
export PATH=$SRCROOT/tools/bin:./node_modules/.bin:$PATH

export ROOT="$SRCROOT/tools/clroot"

export CHAINLINK_PORT=6688
export CHAINLINK_URL=http://127.0.0.1:$CHAINLINK_PORT/

export MIN_OUTGOING_CONFIRMATIONS=1
export MIN_INCOMING_CONFIRMATIONS=1

pushd $SRCROOT >/dev/null

source ./integration/common
source ./tools/bin/clenv

trap cleanup EXIT SIGTERM SIGINT
trap exit_handler EXIT

heading 'Setup...'

if [ "$1" == "parity" ]; then
  export ETH_CHAIN_ID=34055
  launch_parity
else
  export ETH_CHAIN_ID=1337
  launch_gethnet
fi

export CHAINLINK_DEV=true
# launch_chainlink # XXX
# deploy_v05_contracts # XXX

heading 'Running tests...'
pushd integration >/dev/null

./coordinator_test

title 'All tests passed.'
popd >/dev/null
