#!/usr/bin/env bash

set -e

# if you experience OOM on your local machine, set NODE_OPTIONS=--max_old_space_size=5120
pushd contracts
pnpm compile
pnpm coverage
popd

./tools/bin/codecov -f ./contracts/coverage.json
