#!/bin/bash

set -e

yarn solhint "evm/**/*.sol"
yarn solhint "examples/**/*.sol"
yarn lint:evm && yarn lint:examples
# compile contracts
yarn workspace chainlink run truffle build
yarn workspace chainlink-box run truffle compile
# run slither static analyzer
slither evm/ --config-file tools/ci/slither.config.json
slither evm/box --config-file tools/ci/slither.config.json

yarn workspace chainlink test
yarn workspace @chainlink/example-uptime-sla test
yarn workspace @chainlink/example-echo-server test
yarn workspace @chainlink/box test
yarn workspace chainlinkv0.5 test
