#!/bin/bash

set -e

yarn solium --dir evm/
yarn solium --dir examples/
yarn lint:evm && yarn lint:examples

yarn workspace chainlink test
yarn workspace chainlink-uptime-sla test
yarn workspace chainlink-echo-server test
yarn workspace chainlink flatten
yarn workspace chainlink-testnet truffle build
yarn workspace chainlink-box test
