#!/usr/bin/env node

const { abort, port } = require('./common.js')
const { web3 } = require('../evm/app/env.js')

process.env.SOLIDITY_INCLUDE = '../evm/contracts'

const main = async (contractName, txID, fromAddress) => {
  const transaction = await web3.eth
    .getTransactionReceipt(txID)
    .catch(abort('Error getting transaction receipt'))

  let count = 0
  for (let log of transaction.logs) {
    if (log.address.toLowerCase() === fromAddress.toLowerCase()) {
      count += 1
    }
  }
  console.log(count)
}

main(...process.argv.slice(2))
