#!/usr/bin/env node

const { abort } = require('./common.js')
const { provider } = require('../evm/chainlink.config')

process.env.SOLIDITY_INCLUDE = '../evm/contracts'

const main = async (contractName, txID, fromAddress) => {
  const transaction = await provider
    .getTransactionReceipt(txID)
    .catch(abort(`Error getting transaction receipt for ${txID}`))

  let count = 0
  for (let log of transaction.logs) {
    if (log.address.toLowerCase() === fromAddress.toLowerCase()) {
      count += 1
    }
  }
  console.log(count)
}

main(...process.argv.slice(2))
