#!/bin/bash

mkdir tmp

set -e

curl -c tmp/cookiefile \
  -d '{"email":"notreal@fakeemail.ch", "password":"twochains"}' \
  -X POST -H 'Content-Type: application/json' \
   http://localhost:6688/sessions \
   >/dev/null

curl -sS -X POST -H 'Content-Type: application/json' \
  -b tmp/cookiefile \
  -d @./broadcast_logs_job.json http://localhost:6688/v2/specs

