#!/bin/bash

source ./common

title 'Ethlog test.'

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

expected_echo_count=$(expr $(curl -sS $ECHO_SERVER_URL) + 1)
expected_job_count=$(expr $(chainlink -j jobs list | jq length) + 1)

yarn workspace @chainlink/integration run truffle exec scripts/send_ethlog_transaction.js --network test | tee send_ethlog_transaction.log

jid=`cat send_ethlog_transaction.log | grep Job | awk '{print$4}'`

# Check echo count
assert "Echo count" "curl -sS $ECHO_SERVER_URL" $expected_echo_count

# Check job counts
assert "Jobs count" "chainlink -j jobs list | jq length" $expected_job_count

# Check job runs
assert "EthLog Runs count" "chainlink -j runs list --jobid $jid | jq length" 1

# Check that the run completed
assert "Run completed" 'chainlink -j runs list --jobid $jid | jq ".[].result.status" | sed s/\"//g' completed
