#!/bin/bash

source $SRCROOT/integration/common

title 'Flux Monitor test.'

flux_monitor_test() {
  expected_job_count=$(expr $(chainlink -j jobs list | jq length) + 1)
  current_job_run_count=$(expr $(chainlink -j runs list | jq length))
  expected_job_run_count=$((current_job_run_count + 1))
  local log=$LOG_PATH/flux_monitor.log

  # add flux monitor job to CL node
  FLUX_MONITOR_JOB=`cat flux_monitor/fixtures/job.json`
  chainlink jobs create "$FLUX_MONITOR_JOB"

  # Check job counts
  assert "Jobs count" "chainlink -j jobs list | jq length" $expected_job_count

  # Assert no jobs ran yet
  assert "Flux Monitor Runs count" "chainlink -j runs list | jq length" $current_job_run_count

  echo "\n"
  echo "URLS:"
  echo "$EXTERNAL_ADAPTER_URL"
  echo "$ECHO_SERVER_URL"

  # change price feed
  curl \
    -H "Content-Type: application/json" \
    --request PATCH \
    --data '{"result":110}' \
    "$EXTERNAL_ADAPTER_URL/result"

  sleep 5

  # Assert job ran
  assert "Flux Monitor Runs count" "chainlink -j runs list | jq length" $expected_job_run_count



  # yarn workspace @chainlink/integration-scripts send-ethlog-transaction | tee $log

  # jid=`cat $log | grep Job | awk '{print$4}'`

  # # Check echo count
  # assert "Echo count" "curl -sS $ECHO_SERVER_URL" $expected_echo_count

  # # Check job counts
  # assert "Jobs count" "chainlink -j jobs list | jq length" $expected_job_count

  # # Check job runs
  # assert "EthLog Runs count" "chainlink -j runs list --jobid $jid | jq length" 1

  # # Check that the run completed
  # assert "Run completed" 'chainlink -j runs list --jobid $jid | jq ".[].status" | sed s/\"//g' completed
}

flux_monitor_test
