#!/bin/bash

source ./common

title 'Runlog test.'

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

expected_echo_count=$(expr $(curl -sS "$ECHO_SERVER_URL") + 1)
expected_job_count=$(expr $(chainlink -j jobs list | jq length) + 1)

yarn workspace @chainlink/integration run truffle exec scripts/send_runlog_transaction.js --network test | tee $SRCROOT/integration/send_runlog_transaction.log

# Check echo count
assert "Echo count" "curl -sS $ECHO_SERVER_URL" $expected_echo_count

## Check job counts using jq to parse json: https://stedolan.github.io/jq/
assert "Jobs count" "chainlink -j jobs list | jq length" $expected_job_count

# Check job runs
jid=`chainlink -j jobs list | jq 'last | .id' | tr -d '"'`
echo "Test created Job: $jid"
assert "RunLog Runs count" "chainlink -j runs list --jobid $jid | jq 'length'" 1

# Check that the run completed
assert "Run completed" 'chainlink -j runs list --jobid $jid | jq ".[].status" | sed s/\"//g' completed

txid=$(chainlink -j runs list --jobid $jid | jq '.[].result.data.result' | sed 's/"//g')
echo "Test created TX: $txid"

tx_receiver=$(chainlink -j runs list --jobid $jid | jq '.[].result.data.address' | sed 's/"//g')
echo "Test sent TX to: $tx_receiver"

# Check for the Fullfillment event
yarn workspace @chainlink/integration run truffle exec scripts/count_transaction_events.js --network test $txid $RUN_LOG_ADDRESS | tee $SRCROOT/integration/send_runlog_transaction.log
tx_event_count=`cat $SRCROOT/integration/send_runlog_transaction.log | grep "Events from $RUN_LOG_ADDRESS in $txid:" | awk '{print$6}'`
assert "Transaction Events" "echo $tx_event_count" 2

