
[blockchain_a]
  type = "anvil"
  docker_cmd_params = ["-b", "5"]

[jd]
  image = "replace-me"

[workflow_config]
	workflow_name = "abcdefgasd"
  # without 0x prefix!
	feed_id = "018bfe8840700040000000000000000000000000000000000000000000000000"

  use_cre_cli = true
  should_compile_new_workflow = false
  workflow_folder_location = "not-neede-here"

  [workflow_config.dependencies]
  capabilities_version = "v1.0.0-alpha"
  cre_cli_version = "v0.0.2"

  [workflow_config.compiled_config]
    binary_url = "https://gist.githubusercontent.com/Tofel/4eb9378b8bc6f893a3e217f2dbdba95a/raw/cb7b2a56b37e333fe0bdce07b79538c4ce332f5f/binary.wasm.br"
    config_url = "https://gist.githubusercontent.com/Tofel/8d915fe917d6f0fb46c043122b1308f6/raw/f503a91926b7c6959c75dc611504e0f5a4cd35ee/config.json3888664506"

[[nodesets]]
  nodes = 5
  override_mode = "each"
  http_port_range_start = 10100
  name = "workflow"

  [nodesets.db]
    image = "postgres:12.0"
    port = 13000
    volume_name = "workflow_volume"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """