
[blockchain_a]
  type = "anvil"
  docker_cmd_params = ["-b", "5"]

[jd]
  image = "replace-me"

[workflow_config]
	workflow_name = "abcdefgasd"
  # without 0x prefix!
	feed_id = "018bfe8840700040000000000000000000000000000000000000000000000000"

  use_cre_cli = true
  should_compile_new_workflow = false

  [workflow_config.dependencies]
  capabilities_version = "v1.0.0-alpha"
  cre_cli_version = "v0.0.2"

  [workflow_config.compiled_config]
    binary_url = "https://gist.githubusercontent.com/Tofel/ee56735e7814070d63c32e1c4d059a7b/raw/cb7b2a56b37e333fe0bdce07b79538c4ce332f5f/binary.wasm.br"
    config_url = "https://gist.githubusercontent.com/Tofel/f940187351ac8e3d20e7efdf984dbc5d/raw/4bb2de46661e0275ce525ca1a7cc2b5233fa2000/config.json596220333"

[[nodesets]]
  nodes = 5
  override_mode = "each"
  http_port_range_start = 10100
  name = "workflow"

  [nodesets.db]
    image = "postgres:12.0"
    port = 13000
    volume_name = "workflow_volume"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "replace-me"
      capabilities = ["./amd64_cron"]
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """