name: Run Nightly E2E Tests

on:
  push:
    branches:
      - '**'
  schedule:
    # Run every night at midnight UTC (0:00 AM)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Useful when running the workflow manually
    inputs:
      chainlink_version:
        description: 'Enter Chainlink version to use for the tests. Example: "v2.10.0" or sha'
        required: true
        type: string
        default: develop
      slack_notification_after_tests:
        description: 'Notify on Slack after tests'
        required: false
        type: string

concurrency:
  group: ${{ github.ref }}-${{ github.repository }}-${{ github.event_name }}--e2e-tests-${{ inputs.distinct_run_name }}
  cancel-in-progress: true

env:
  # for run-test variables and environment
  ENV_JOB_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink-tests:${{ inputs.evm-ref || github.sha }}
  CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
  TEST_SUITE: smoke
  TEST_ARGS: -test.timeout 12m
  INTERNAL_DOCKER_REPO: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com
  MOD_CACHE_VERSION: 2
  COLLECTION_ID: chainlink-nightly-tests

jobs:
  nightly-test:
    environment: integration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: ccip_token_transfer_test
            id: smoke/ccip/ccip_token_transfer_test.go:*
            test_cmd: cd integration-tests/smoke/ccip && go test ccip_token_transfer_test.go -timeout 16m -test.parallel=1 -count=1 -json
            config: ../../testconfig/ccip/ccip-default-ctfv2.toml
    name: ${{ matrix.test.name }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.2.1
        with:
          persist-credentials: false
          repository: smartcontractkit/chainlink
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.PUBLIC_AWS_ECR_ROLE }}
          aws-region: us-east-1
      - name: Authenticate to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public
      - name: Setup Github Token
        id: get-gh-token
        uses: smartcontractkit/.github/actions/setup-github-token@ef78fa97bf3c77de6563db1175422703e9e6674f # setup-github-token@0.2.1
        with:
          aws-role-arn: ${{ secrets.AWS_OIDC_GLOBAL_READ_ONLY_TOKEN_ISSUER_ROLE_ARN }}
          aws-lambda-url: ${{ secrets.AWS_INFRA_RELENG_TOKEN_ISSUER_LAMBDA_URL }}
          aws-region: ${{ secrets.AWS_REGION }}
          set-git-config: "true"
      - name: Build Chainlink Image
        uses: ./.github/actions/build-chainlink-image
        with:
          tag_suffix: ""
          dockerfile: core/chainlink.Dockerfile
          git_commit_sha: ${{ github.sha }}
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.8
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('integration-tests/go.sum') }}-${{ runner.os }}-ccip-nightly-tests
          restore-keys: |
            go-modules-${{ runner.os }}-ccip-nightly-tests
            go-modules-${{ runner.os }}
      - name: Install dependencies
        run: go mod download
      - name: Run System Tests
        env:
          CTF_CONFIGS: ${{ matrix.test.config }}
          CTF_JD_IMAGE: ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/job-distributor:0.0.6
          CTF_CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION}}.amazonaws.com/chainlink:${{ github.sha }}
          LOKI_TENANT_ID: ${{ secrets.LOKI_TENANT_ID }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
          CCIP_V16_TEST_ENV: anvil-docker
        run: ${{ matrix.test.test_cmd}}
#          go test -timeout ${{ matrix.test.timeout }} -v -count ${{ matrix.test.count }} -run ${{ matrix.test.name }} -parallel ${{ matrix.test.parallel }}
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: container-logs-${{ matrix.test.name }}
          path: framework/examples/myproject/logs
          retention-days: 1