#
# This action creates or updates a Release Preview PR that shows which changes are going to be part of the next release.
#

name: Release Preview - Changeset

on:
  push:
    branches:
      - develop

jobs:
  changesets-release-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: change
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            core-changeset:
              - '.changeset/**'

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        if: steps.change.outputs.core-changeset == 'true'

      - name: Setup node
        uses: actions/setup-node@v7
        if: steps.change.outputs.core-changeset == 'true'
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Generate new changelog
        if: steps.change.outputs.core-changeset == 'true'
        id: changelog
        run: pnpm install && ./tools/ci/format_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release preview PR
        if: steps.change.outputs.core-changeset == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            .changeset/**
            CHANGELOG.md
          commit-message: "changeset: release preview"
          committer: app-token-issuer-releng[bot] <app-token-issuer-releng[bot]@users.noreply.github.com>
          branch: changesets/release-preview
          title: "[DO NOT MERGE] Changeset Release Preview - v${{ steps.changelog.outputs.version }}"
          body: ${{ steps.changelog.outputs.pr_body }}
          draft: true
          labels: |
            release-preview
            do-not-merge
