      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: smartcontractkit/chainlink
          fetch-depth: 0 # ensure full history for commit comparison

      - name: Ensure develop branch is fetched
        run: |
          git fetch origin develop:origin/develop || echo "develop already up-to-date"

      - name: Detect Changed Paths (match-some)
        id: match-some
        uses: dorny/paths-filter@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.sha }}
          base: origin/develop
          filters: |
            deployment:
              - 'deployment/**'
            workflow:
              - '.github/workflows/ci-core.yml'
              - '.github/actions/**'

      - name: Detect Changed Paths (match-every)
        id: match-every
        uses: dorny/paths-filter@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.sha }}
          base: origin/develop
          list-files: json
          filters: |
            core-non-ignored:
              - '**'
              - '!deployment/**'
              - '!integration-tests/**'
              - '!tools/secrets/**'
              - '!tools/docker/**'
              - '!tools/benchmark/**'
              - '!**/README.md'
              - '!**/CHANGELOG.md'
              - '!*.nix'
              - '!sonar-project.properties'
              - '!nix.conf'
              - '!nix-darwin-shell-hook.sh'
              - '!LICENSE'
              - '!.github/**'
              - '!core/scripts/cre/environment/examples/workflows/**'
            all:
              - '**'
