name: gomod-local-update

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Build binary
        run: |
          go build -o dist/gomod-local-update \
            ./tools/gomod-local-update/cmd/gomod-local-update
