name: gomod-required-updater

on:
  merge_group:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Build binary
        run: |
          go build -o dist/gomod-required-updater \
            ./tools/gomod-required-updater/cmd/gomod-required-updater
