name: Cleanup integration deployments
on:
  workflow_dispatch:
  schedule:
    # every 10 mins
    - cron: "*/10 * * * *"

jobs:
  cleanup:
    name: Clean up integration environment deployments
    runs-on: ubuntu-latest
    steps:
      - name: Clean up integration environment
        uses: smartcontractkit/.github/actions/delete-deployments@delete-deployments/v1
        with:
          environment: integration
          # Delete 300 deployments at a time
          num-of-pages: 3
          # We start with page 2 because usually the first 200 deployments are still active, so we cannot delete them
          starting-page: 2
