name: dependabump

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5" # every week-day at midnight

permissions: {}

jobs:
  dependabump:
    permissions:
      contents: write
      pull-requests: write
      actions: read
      security-events: read
      vulnerability-alerts: read
    uses: smartcontractkit/.github/.github/workflows/reusable-dependabump.yml@0e6fc392912f6f19cb8b3607f6a7c4edc1d9bfec
    secrets:
      SLACK_TOKEN: ${{ secrets.DEPENDABUMP_SLACK_API_KEY }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_TEAM_CORE_CHANNEL_ID }}
