name: OCR2 Upgrade Compatibility Test

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: devenv

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  compatibility:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu24.04-16cores-64GB # ghv-ignore!
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Install Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: "1.40.0"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_SDLC_ECR_READONLY_ARN }}
          aws-region: us-west-2

      - name: Authenticate to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          cache: true
          go-version-file: devenv/go.mod
          cache-dependency-path: devenv/go.sum

      - name: Download Go dependencies
        run: |
          go mod download

      - name: Install CTF binary
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CTF_TAG: "framework/v0.14.6"
        run: |
          echo "::startgroup::Install CTF binary"
          mkdir -p bin
          gh release download "${CTF_TAG}" --pattern "framework-v*-linux-amd64.tar.gz" --clobber --repo smartcontractkit/chainlink-testing-framework -O ctf.tar.gz
          tar -xzf ctf.tar.gz
          mv ctf bin/ctf
          chmod +x bin/ctf
          echo "::endgroup::"

      # TODO: this is only for demo purposes, remove after we re-tag properly
      - name: Tag compatible versions
        run: |
          git tag 2.35.0+test fc851870f7
          git tag v2.34.0+test b76d5debbe
          git tag 2.33.0+test 95d4c2c423
          git tag v2.32.0+test 73c2710e55

      - name: Run compat test
        working-directory: devenv
        shell: bash
        env:
          CTF_LOG_LEVEL: debug
          FAKE_SERVER_IMAGE: ${{ secrets.FAKE_SERVER_IMAGE }}
          REGISTRY: ${{ secrets.REGISTRY_SDLC }}/chainlink
        run: |
          ./bin/ctf compat backward \
          --registry $REGISTRY \
          --envcmd "cl u env.toml,products/ocr2/basic.toml" \
          --testcmd "cl test ocr2 TestSmoke/rounds" \
          --include-tags +test \
          --nodes 3 \
          --versions_back 3

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: container-logs-smoke
          path: devenv/tests/ocr2/logs
          retention-days: 3
