name: Find Flaky Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      dir:
        description: The directory to find flaky tests in (core/services/...)
        required: true
        type: string
        default: "core/..."
      iterations:
        description: The number of iterations to run the tests for
        required: true
        type: number
        default: 10
      parallel_iterations:
        description: The number of iterations to run in parallel
        required: false
        type: number
        default: 1

jobs:
  find-flaky-tests:
    name: Find Flaky Tests
    runs-on: runs-on=${{ github.run_id
      }}-diagnose/cpu=48/ram=96/family=c6id+c5ad/spot=false/image=ubuntu24-full-x64/extras=s3-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: smartcontractkit/chainlink
          ref: ${{ github.sha }}
      - name: Enable S3 Cache for Self-Hosted Runners
        uses: runs-on/action@742bf56072eb4845a0f94b3394673e4903c90ff0 # v2.1.0
        with:
          metrics: cpu,network,memory,disk
      - name: Run `diagnose`
        run: |
          go -C tools/test run . diagnose --iterations ${{ inputs.iterations }} --parallel-iterations ${{ inputs.parallel_iterations }} -- ${{ inputs.dir }}
      - name: Upload Results
        uses: actions/upload-artifact@v7
        with:
          name: flaky-tests-results
          path: ./diagnose-*
          if-no-files-found: error
