name: Go Module Cache

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: go-mod-cache-${{ github.ref }}
  cancel-in-progress: false

jobs:
  go-cache:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            suffix: "Core (GitHub-hosted)"
            go-mod-directory: "."
          - runs-on: ubuntu-latest
            suffix: "Deployment (GitHub-hosted)"
            go-mod-directory: "deployment/"
          - runs-on: [self-hosted, c6id]
            suffix: "Core (Self-hosted)"
            go-mod-directory: "."
          - runs-on: [self-hosted, c6id]
            suffix: "Deployment (Self-hosted)"
            go-mod-directory: "deployment/"

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles(format('{0}/**/go.sum', matrix.go-mod-directory)) }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Download dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: ${{ matrix.go-mod-directory }}
        run: |
          echo "::group::go mod download"
          go mod download
          echo "::endgroup::"

      - name: Install LOOP plugins
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          echo "::group::Install LOOP plugins"
          make install-plugins-public
          echo "::endgroup::"

      - name: Install testing tools
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          echo "::group::Install testing tools"
          go install gotest.tools/gotestsum@v1.12.3
          echo "::endgroup::"
