name: Legacy System Tests

on:
  workflow_dispatch:
    inputs:
      chainlink_image_repository_path:
        description: "ECR repository name used to compose image with chainlink_image_tag (for example: chainlink-integration-tests or chainlink or chainlink/chainlink)."
        required: true
        type: string
      chainlink_image_tag:
        required: true
        type: string
        description: "Chainlink image tag to use."
      ecr:
        type: choice
        options:
          - "sdlc"
          - "public"
        required: true
        default: "sdlc"
        description: "Whether to use the SDLC (sdlc) or public ECR registry (public) for the Chainlink image."
      chainlink_version:
        required: false
        type: string
        description: "The version of Chainlink repository to use for the tests. If empty, defaults to github.sha."
        default: ""
  workflow_call:
    inputs:
      chainlink_image_repository_path:
        description: "ECR repository name used to compose image with chainlink_image_tag (for example: chainlink-integration-tests or chainlink or chainlink/chainlink)."
        required: true
        type: string
      chainlink_image_tag:
        required: true
        type: string
        description: "Chainlink image tag to use."
      ecr:
        type: string
        required: true
        default: "sdlc"
        description: "Whether to use the SDLC (sdlc) or public ECR registry (public) for the Chainlink image."
      chainlink_version:
        required: false
        type: string
        description: "The version of Chainlink repository to use for the tests. If empty, defaults to github.sha."
        default: ""

defaults:
  run:
    working-directory: devenv

concurrency:
  group: legacy-system-tests-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  summary:
    name: "Build Information"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: "integration"
      deployment: false
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.chainlink_version || github.sha }}
      # we cannot pass this resolved image to `test-nightly` job, because when it contains secrets
      # github sets its value to an empty string to avoid leaking secrets.
      - name: Resolve Chainlink image
        id: resolve-chainlink-image
        working-directory: .github/scripts
        shell: bash
        env:
          CHAINLINK_IMAGE_REPO_PATH: ${{ inputs.chainlink_image_repository_path }}
          CHAINLINK_IMAGE_TAG: ${{ inputs.chainlink_image_tag }}
          ECR_TYPE: ${{ inputs.ecr }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
        run: |
          resolved_image="$(bash resolve-chainlink-image.sh)"
          [[ -n "$resolved_image" ]] || { echo "resolved_image is empty"; exit 1; }
          echo "$resolved_image"
          echo "resolved_image=${resolved_image}" >> "${GITHUB_OUTPUT}"
      - name: Print Summary
        working-directory: .
        run: |
          echo "**Image:** \`${{ steps.resolve-chainlink-image.outputs.resolved_image }}\`" >> $GITHUB_STEP_SUMMARY

  test-nightly:
    name: ${{ matrix.display_name }}
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.runner }}
    environment:
      name: integration
      deployment: false
    strategy:
      fail-fast: false
      matrix:
        include:
          # quick feature tests
          - display_name: "Test Multiple JobDistributors"
            testcmd: "go test -v -run TestMultipleJobDistributors"
            envcmd: "cl u env.toml,products/ocr2/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "features"
            logs_archive_name: "multiple-jd"
          - display_name: "Test Reorg Finality Violation"
            testcmd: "go test -v -run TestReorgHeadTrackerFinalityViolation"
            envcmd: "cl u env.toml,env-geth.toml,products/ocr2/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "features"
            logs_archive_name: "reorg-finality-violation"
          # smoke tests, small legacy products
          - display_name: "Test Cron Smoke"
            testcmd: "go test -v -run TestSmoke"
            envcmd: "cl u env.toml,products/cron/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "cron"
            logs_archive_name: "cron"
          - display_name: "Test Direct Request Smoke"
            testcmd: "go test -v -run TestSmoke"
            envcmd: "cl u env.toml,products/directrequest/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "directrequest"
            logs_archive_name: "directrequest"
          - display_name: "Test Flux Smoke"
            testcmd: "go test -v -run TestSmoke"
            envcmd: "cl u env.toml,products/flux/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "flux"
            logs_archive_name: "flux"
          - display_name: "Test VRF Smoke"
            testcmd: "go test -v -timeout 10m -run TestVRFBasic\\|TestVRFJobReplacement"
            envcmd: "cl u env.toml,products/vrf/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "vrf"
            logs_archive_name: "vrf"
          - display_name: "Test DF1 (OCR2) Smoke"
            testcmd: "go test -v -timeout 20m -run TestSmoke/rounds"
            envcmd: "cl u env.toml,products/ocr2/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "ocr2"
            logs_archive_name: "df1-smoke"
          - display_name: "Test DF1 (OCR2, Forwarders) Smoke"
            testcmd: "go test -v -timeout 20m -run TestSmoke/rounds"
            envcmd: "cl u env.toml,products/ocr2/basic.toml,products/ocr2/forwarders.toml"
            runner: "ubuntu-latest"
            tests_dir: "ocr2"
            logs_archive_name: "df1-smoke-forwarders"
          # smoke tests, medium legacy products
          - display_name: "Automation Smoke Test, Registry 2.0"
            testcmd: "go test -v -timeout 30m -run TestRegistry_2_0"
            envcmd: "cl u env.toml,products/automation/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "automation"
            logs_archive_name: "automation-smoke-2_0"
          - display_name: "Automation Smoke Test, Registry 2.1"
            testcmd: "go test -v -timeout 30m -run TestRegistry_2_1"
            envcmd: "cl u env.toml,products/automation/basic.toml"
            runner: "ubuntu-latest"
            tests_dir: "automation"
            logs_archive_name: "automation-smoke-2_1"
          - display_name: "Automation Smoke Test, Registry 2.2"
            testcmd: "go test -v -timeout 30m -run TestRegistry_2_2"
            envcmd: "cl u env.toml,products/automation/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "automation"
            logs_archive_name: "automation-smoke-2_2"
          - display_name: "Automation Smoke Test, Registry 2.3"
            testcmd: "go test -v -timeout 30m -run TestRegistry_2_3"
            envcmd: "cl u env.toml,products/automation/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "automation"
            logs_archive_name: "automation-smoke-2_3"
          - display_name: "Keepers Smoke Tests 1"
            testcmd: "go test -v -timeout 1h -run TestKeeperBasic\\|TestKeeperSimulation\\|TestKeeperCheckPerformGasLimit\\|TestKeeperRegisterUpkeep\\|TestKeeperAddFunds\\|TestKeeperRemove\\|TestKeeperPauseRegistry\\|TestKeeperMigrateRegistry\\|TestKeeperJobReplacement"
            envcmd: "cl u env.toml,products/keepers/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "keepers"
            logs_archive_name: "keepers-smoke-1"
          - display_name: "Keepers Smoke Tests 2"
            testcmd: "go test -v -timeout 1h -run TestKeeperNodeDown"
            envcmd: "cl u env.toml,products/keepers/low_bcptr.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "keepers"
            logs_archive_name: "keepers-smoke-2"
          - display_name: "Keepers Smoke Tests 3"
            testcmd: "go test -v -timeout 1h -run TestKeeperPauseUnPauseUpkeep\\|TestKeeperUpdateCheckData"
            envcmd: "cl u env.toml,products/keepers/low_bcptr.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "keepers"
            logs_archive_name: "keepers-smoke-3"
          - display_name: "Keepers Smoke Tests 4"
            testcmd: "go test -v -timeout 1h -run TestKeeperBlockCountPerTurn"
            envcmd: "cl u env.toml,env-geth.toml,products/keepers/high_bcptr.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "keepers"
            logs_archive_name: "keepers-smoke-4"
          - display_name: "Test VRFv2Plus Smoke"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusSmoke"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-smoke"
          - display_name: "Test VRFv2Plus Multiple Sending Keys"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusMultipleSendingKeys"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/two_keys.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-multiple-sending-keys"
          - display_name: "Test VRFv2Plus With BHS"
            testcmd: "go test -v -timeout 30m -run TestVRFV2PlusWithBHS"
            envcmd: "cl u env-vrf2plus-bhX.toml,products/vrfv2plus/bhs.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-with-bhs"
          - display_name: "Test VRFv2Plus With BHF"
            testcmd: "go test -v -timeout 30m -run TestVRFV2PlusWithBHF"
            envcmd: "cl u env-vrf2plus-bhX.toml,env-geth.toml,products/vrfv2plus/bhf.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-with-bhf"
          - display_name: "Test VRFv2Plus Replay After Timeout"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusReplayAfterTimeout"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/replay.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-replay-after-timeout"
          - display_name: "Test VRFv2Plus Pending Block Simulation And Zero Confirmation Delays"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusPendingBlockSimulationAndZeroConfirmationDelays"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/pending_block.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-pending-block-simulation-and-zero-confirmation-delays"
          - display_name: "Test VRFv2Plus Migration"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusMigration"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-migration"
          - display_name: "Test VRFv2Plus Batch Fulfillment"
            testcmd: "go test -v -timeout 30m -run TestVRFv2PlusBatchFulfillment"
            envcmd: "cl u env-vrf2plus.toml,products/vrfv2plus/batch.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2plus"
            logs_archive_name: "vrfv2plus-batch-fulfillment"
          - display_name: "Test VRFv2 (coordinator v2) Smoke"
            testcmd: "go test -v -timeout 30m -run TestVRFv2Basic"
            envcmd: "cl u env-vrfv2.toml,products/vrfv2/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2"
            logs_archive_name: "vrfv2-smoke"
          - display_name: "Test VRFv2 Multiple Sending Keys"
            testcmd: "go test -v -timeout 30m -run TestVRFv2MultipleSendingKeys"
            envcmd: "cl u env-vrfv2.toml,products/vrfv2/two_keys.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2"
            logs_archive_name: "vrfv2-multiple-sending-keys"
          - display_name: "Test VRFv2 With BHS"
            testcmd: "go test -v -timeout 30m -run TestVRFV2WithBHS"
            envcmd: "cl u env-vrfv2-bhs.toml,products/vrfv2/bhs.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2"
            logs_archive_name: "vrfv2-with-bhs"
          - display_name: "Test VRFv2 Batch Fulfillment"
            testcmd: "go test -v -timeout 30m -run TestVRFv2BatchFulfillmentEnabledDisabled"
            envcmd: "cl u env-vrfv2.toml,products/vrfv2/basic.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "vrfv2"
            logs_archive_name: "vrfv2-batch-fulfillment"
          - display_name: "Test LogPoller Fixed Depth"
            testcmd: "go test -v -timeout 30m -run TestLogPoller"
            envcmd: "cl u env.toml,tests/logpoller/fixed_depth.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "logpoller"
            logs_archive_name: "logpoller-fixed-depth"
          - display_name: "Test LogPoller Finality Tag"
            testcmd: "go test -v -timeout 30m -run TestLogPoller"
            envcmd: "cl u env.toml,tests/logpoller/finality_tag.toml"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "logpoller"
            logs_archive_name: "logpoller-finality-tag"
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.chainlink_version || github.sha }}

      - name: Install Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: "1.40.0"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_CTF_READ_ACCESS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Login to Amazon ECRs (private)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1
        with:
          registries: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
        env:
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}

      - name: Login to Amazon ECR (public)
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1
        with:
          registry-type: public
        env:
          AWS_REGION: us-east-1

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache: true
          go-version-file: devenv/go.mod
          cache-dependency-path: devenv/go.sum

      - name: Download Go dependencies
        run: |
          go mod download

      - name: Resolve Chainlink image
        id: resolve-chainlink-image
        working-directory: .github/scripts
        shell: bash
        env:
          CHAINLINK_IMAGE_REPO_PATH: ${{ inputs.chainlink_image_repository_path }}
          CHAINLINK_IMAGE_TAG: ${{ inputs.chainlink_image_tag }}
          ECR_TYPE: ${{ inputs.ecr }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
        run: |
          resolved_image="$(bash resolve-chainlink-image.sh)"
          [[ -n "$resolved_image" ]] || { echo "resolved_image is empty"; exit 1; }
          echo "$resolved_image"
          echo "resolved_image=${resolved_image}" >> "${GITHUB_OUTPUT}"

      - name: Set environment variables
        run: |
          echo "CHAINLINK_IMAGE=${{ steps.resolve-chainlink-image.outputs.resolved_image }}" >> $GITHUB_ENV
      - name: Setup environment
        env:
          FAKE_SERVER_IMAGE: ${{ secrets.FAKE_SERVER_IMAGE }}
        run: |
          cd cmd/cl && go install . && cd -
          ENV_CMD="${{ matrix.envcmd }}"
          echo "Setting up environment with: $ENV_CMD"
          eval "$ENV_CMD"

      - name: Run tests
        working-directory: devenv/tests/${{ matrix.tests_dir }}
        env:
          CURRENT_TEST: ${{ matrix.testcmd }}
        run: |
          TESTCMD="${{ matrix.testcmd }}"
          echo "Running tests for: $CHAINLINK_IMAGE, test: $TESTCMD"
          eval "$TESTCMD"

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: system-tests-container-logs-${{ matrix.logs_archive_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: devenv/tests/${{ matrix.tests_dir }}/logs
          retention-days: 3
