name: Legacy Non Functional Tests

on:
  workflow_dispatch:
    inputs:
      chainlink_image_repository_path:
        description: "ECR repository name used to compose image with chainlink_image_tag (for example: chainlink-integration-tests or chainlink or chainlink/chainlink)."
        required: true
        type: string
      chainlink_image_tag:
        required: true
        type: string
        description: "Chainlink image tag to use."
      ecr:
        type: choice
        options:
          - "sdlc"
          - "public"
        required: true
        default: "sdlc"
        description: "Whether to use the SDLC (sdlc) or public ECR registry (public) for the Chainlink image."
      chainlink_version:
        required: false
        type: string
        description: "The version of Chainlink repository to use for the tests. If empty, defaults to github.sha."
        default: ""
  workflow_call:
    inputs:
      chainlink_image_repository_path:
        description: "ECR repository name used to compose image with chainlink_image_tag (for example: chainlink-integration-tests or chainlink or chainlink/chainlink)."
        required: true
        type: string
      chainlink_image_tag:
        required: true
        type: string
        description: "Chainlink image tag to use."
      ecr:
        type: string
        required: true
        default: "sdlc"
        description: "Whether to use the SDLC (sdlc) or public ECR registry (public) for the Chainlink image."
      chainlink_version:
        required: false
        type: string
        description: "The version of Chainlink repository to use for the tests. If empty, defaults to github.sha."
        default: ""

defaults:
  run:
    working-directory: devenv

concurrency:
  group: legacy-non-functional-tests-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  summary:
    name: "Build Information"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: "integration"
      deployment: false
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.chainlink_version || github.sha }}
      # we cannot pass this resolved image to `test-nightly` job, because when it contains secrets
      # github sets its value to an empty string to avoid leaking secrets.
      - name: Resolve Chainlink image
        id: resolve-chainlink-image
        working-directory: .github/scripts
        shell: bash
        env:
          CHAINLINK_IMAGE_REPO_PATH: ${{ inputs.chainlink_image_repository_path }}
          CHAINLINK_IMAGE_TAG: ${{ inputs.chainlink_image_tag }}
          ECR_TYPE: ${{ inputs.ecr }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
        run: |
          resolved_image="$(bash resolve-chainlink-image.sh)"
          [[ -n "$resolved_image" ]] || { echo "resolved_image is empty"; exit 1; }
          echo "$resolved_image"
          echo "resolved_image=${resolved_image}" >> "${GITHUB_OUTPUT}"
      - name: Print Summary
        working-directory: .
        run: |
          echo "**Image:** \`${{ steps.resolve-chainlink-image.outputs.resolved_image }}\`" >> $GITHUB_STEP_SUMMARY

  test-nightly:
    name: ${{ matrix.display_name }}
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.runner }}
    environment:
      name: integration
      deployment: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - display_name: "Automation Soak Test"
            testcmd: "go test -v -timeout 4h -run TestLoad/registry_2_1"
            envcmd: "cl u env.toml,env-geth.toml,products/automation/soak.toml; cl obs up -f"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "automation"
            logs_archive_name: "automation-soak"
          - display_name: "Test DF1 (OCR2) Soak"
            testcmd: "go test -v -timeout 4h -run TestOCR2Soak/clean"
            envcmd: "cl u env.toml,products/ocr2/basic.toml,products/ocr2/soak.toml; cl obs up -f"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "ocr2"
            logs_archive_name: "df1-soak"
          - display_name: "Test DF1 (OCR2) Chaos"
            testcmd: "go test -v -timeout 30m -run TestOCR2Chaos"
            envcmd: "cl u env.toml,products/ocr2/basic.toml; cl obs up -f"
            runner: "ubuntu24.04-16cores-64GB"
            tests_dir: "ocr2"
            logs_archive_name: "df1-chaos"
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.chainlink_version || github.sha }}

      - name: Install Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: "1.40.0"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_CTF_READ_ACCESS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Login to Amazon ECRs (private)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1
        with:
          registries: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
        env:
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}

      - name: Login to Amazon ECR (public)
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1
        with:
          registry-type: public
        env:
          AWS_REGION: us-east-1

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache: true
          go-version-file: devenv/go.mod
          cache-dependency-path: devenv/go.sum

      - name: Download Go dependencies
        run: |
          go mod download

      - name: Resolve Chainlink image
        id: resolve-chainlink-image
        working-directory: .github/scripts
        shell: bash
        env:
          CHAINLINK_IMAGE_REPO_PATH: ${{ inputs.chainlink_image_repository_path }}
          CHAINLINK_IMAGE_TAG: ${{ inputs.chainlink_image_tag }}
          ECR_TYPE: ${{ inputs.ecr }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
        run: |
          resolved_image="$(bash resolve-chainlink-image.sh)"
          [[ -n "$resolved_image" ]] || { echo "resolved_image is empty"; exit 1; }
          echo "$resolved_image"
          echo "resolved_image=${resolved_image}" >> "${GITHUB_OUTPUT}"

      - name: Set environment variables
        run: |
          echo "CHAINLINK_IMAGE=${{ steps.resolve-chainlink-image.outputs.resolved_image }}" >> $GITHUB_ENV
      - name: Setup environment
        env:
          FAKE_SERVER_IMAGE: ${{ secrets.FAKE_SERVER_IMAGE }}
        run: |
          cd cmd/cl && go install . && cd -
          ENV_CMD="${{ matrix.envcmd }}"
          echo "Setting up environment with: $ENV_CMD"
          eval "$ENV_CMD"

      - name: Run tests
        working-directory: devenv/tests/${{ matrix.tests_dir }}
        env:
          CURRENT_TEST: ${{ matrix.testcmd }}
        run: |
          TESTCMD="${{ matrix.testcmd }}"
          echo "Running tests for: $CHAINLINK_IMAGE, test: $TESTCMD"
          eval "$TESTCMD"

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: non-functional-tests-container-logs-${{ matrix.logs_archive_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: devenv/tests/${{ matrix.tests_dir }}/logs
          retention-days: 3

      - name: Upload Go pprof
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: alloc-${{ matrix.logs_archive_name }}-${{ github.run_id }}-${{ github.run_attempt }}.pprof
          path: devenv/tests/${{ matrix.tests_dir }}/alloc.pprof
          retention-days: 7
