name: Lint GH Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.y*ml'
      - '.github/actions/**/action.y*ml'

permissions: {}

jobs:
  lint_workflows:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
