name: Lint GH Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.y*ml'
      - '.github/actions/**/action.y*ml'
      - '.github/actionlint.yml'

permissions: {}

jobs:
  lint_workflows:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Check out Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
