name: On Demand OCR Soak Test
on:
  push:
    tags:
      # Run soak on release tags
      - 'v*'

  workflow_dispatch:
    inputs:
      testToRun:
        description: Test to run (from .github/e2e-tests.yml)
        required: true
        default: soak/ocr_test.go:TestOCRv2Soak
        type: choice
        options:
          - soak/ocr_test.go:TestOCRv1Soak
          - soak/ocr_test.go:TestOCRv2Soak
          - soak/ocr_test.go:TestForwarderOCRv1Soak
          - soak/ocr_test.go:TestForwarderOCRv2Soak
          - soak/ocr_test.go:TestOCRSoak_GethReorgBelowFinality_FinalityTagDisabled
          - soak/ocr_test.go:TestOCRSoak_GethReorgBelowFinality_FinalityTagEnabled
          - soak/ocr_test.go:TestOCRSoak_GasSpike
          - soak/ocr_test.go:TestOCRSoak_ChangeBlockGasLimit
          - soak/ocr_test.go:TestOCRSoak_RPCDownForAllCLNodes
          - soak/ocr_test.go:TestOCRSoak_RPCDownForHalfCLNodes
      chainlink_version:
        description: Version to test (e.g. "v2.25.0-beta.0", "develop", etc.)
        required: true
        default: develop
        type: string
      test_config_override_path:
        description: Path to the override test config TOML (defaults to OCR2 on Eth Sepolia, 12h soak)
        required: false
        default: 'integration-tests/testconfig/ocr2/overrides/ethereum_sepolia_12h.toml'
        type: string
      test_secrets_override_key:
        description: Test secrets (default EOA - 0x663d14907663dC0D2bC3A3b9Ad61c10fa9B0fc08 on Eth Sepolia)
        required: false
        type: string
      team:
        description: Team (e.g. BIX, CCIP, CRE, etc.)
        required: true
        type: string
      slackMemberID:
        description: Slack Member ID (to tag when results published in \#test-run-notifications Slack channel).
        required: true
        default: U01A2B2C3D4

jobs:
  # Based on the `inputs.chainlink_version` define whether to:
  # - use a private or public ECR registry
  # - skip image build if public ECR registry is used
  version-to-docker-registry:
    name: Define Image Location Based on Version
    runs-on: ubuntu-latest
    outputs:
      skip_image_build: ${{ steps.set-registry-type.outputs.skip_image_build }}
    env:
      GIT_REF: ${{ github.ref }}
      GIT_TAG: ${{ github.ref_name }}
    steps:
      - name: Select private or public ECR registry based on version provided
        id: set-registry-type
        shell: bash
        run: |
          # If running on a version or tag starting with `v` use public ECR registry
          # Validate (regexp) if the value matches format `v<number>.<everything else>`
          if [[ "${{ inputs.chainlink_version }}" =~ ^v[0-9]+\..*$ ]]; then
            echo "skip_image_build=true" >> $GITHUB_OUTPUT
            echo "Detected version: '${{ inputs.chainlink_version }}'. Public ECR registry will be used. No image will be built."
          elif [[ -z "${{ inputs.chainlink_version }}" && "$GIT_REF" =~ /tags/ ]]; then
            # Validate if the tag is a 'core' version
            if [[ "$GIT_TAG" =~ ^v[0-9]+\..*$ ]]; then
              echo "skip_image_build=true" >> $GITHUB_OUTPUT
              echo "Running on a tag: '$GIT_TAG'. Public ECR registry will be used. No image will be built."
              exit 0
            fi
          elif [[ -z "${{ inputs.chainlink_version }}" && ! "$GIT_REF" =~ /tags/ ]]; then
            echo "Error: 'chainlink_version' input or GH tag is required."
            exit 1
          else
            echo "skip_image_build=false" >> $GITHUB_OUTPUT
            echo "Detected version: '${{ inputs.chainlink_version }}'. Private ECR registry will be used. Image will be built."
          fi

  # Prefix `v` should be stripped for Docker images
  resolve-docker-version:
    name: Resolve Chainlink Docker Version
    runs-on: ubuntu-latest
    needs: version-to-docker-registry
    outputs:
      chainlink_image_version: ${{ steps.resolve.outputs.chainlink_image_version }}
    env:
      VERSION: ${{ inputs.chainlink_version || github.ref_name }}
    steps:
      - name: Validate if version provided is a 'core' version
        if: ${{ needs.version-to-docker-registry.outputs.skip_image_build == 'true' }}
        id: is-core
        run: |
          # Examples: `v2.23.1-beta.0`, `v2.23.1-rc.1`
          if [[ "$VERSION" =~ v[0-9]+\.[0-9]+\.[0-9]+-beta.*$ || "$VERSION" =~ v[0-9]+\.[0-9]+\.[0-9]+-rc.*$ ]]; then
            echo "is-core=true" >> $GITHUB_OUTPUT
            echo "Used version '$VERSION' is a 'core' version."
          else
            echo "is-core=false" >> $GITHUB_OUTPUT
            echo "Used version '$VERSION' is NOT a 'core' version."
          fi

      - name: Resolve version for Core Docker image
        id: resolve
        shell: bash
        run: |
          if [[ ${{ steps.is-core.outputs.is-core == 'true' }} ]]; then
            # strip the `v` prefix from the version
            version="${VERSION#v}"
            echo "Resolved 'core' image version: '$version'."
            echo "chainlink_image_version=$version" >> $GITHUB_OUTPUT
          else
            version="$VERSION"
            echo "Using initially provided image version: '$version'."
            echo "chainlink_image_version=$version" >> $GITHUB_OUTPUT
          fi

  # Set provided or default test secrets
  set-test-secrets:
    name: Set Test Secrets
    runs-on: ubuntu-latest
    needs: [version-to-docker-registry]
    outputs:
      test_secrets_override_key: ${{ steps.test-secrets.outputs.test_secrets_override_key }}
    steps:
      - name: Set test secrets
        id: test-secrets
        run: |
          # If test_secrets_override_key is not provided, use the default secrets
          # default secrets selection depends on image location (public or private ECR)
          if [[ -z "${{ inputs.test_secrets_override_key }}" ]]; then
            echo "No test_secrets_override_key provided. Using default secrets based on image location."
            if [[ "${{ needs.version-to-docker-registry.outputs.skip_image_build }}" == 'true' ]]; then
              echo "test_secrets_override_key=aws:testsecrets/DEFAULT_TEST_SECRETS" >> $GITHUB_OUTPUT
              echo "Using default secrets for PUBLIC ECR registry."
            else
              echo "test_secrets_override_key=aws:testsecrets/PRIVATE_DEFAULT_TEST_SECRETS" >> $GITHUB_OUTPUT
              echo "Using default secrets for PRIVATE ECR registry."
            fi
          else
            echo "test_secrets_override_key=${{ inputs.test_secrets_override_key }}" >> $GITHUB_OUTPUT
            echo "Using provided test secrets."
          fi

  run-e2e-tests-workflow:
    name: Run E2E Tests
    needs: [version-to-docker-registry, resolve-docker-version, set-test-secrets ]
    uses: smartcontractkit/.github/.github/workflows/run-e2e-tests.yml@1e6b821dc36a55e338d6bdbda1320a0db93b729d
    with:
      chainlink_version: ${{ needs.resolve-docker-version.outputs.chainlink_image_version }}
      test_path: .github/e2e-tests.yml
      test_ids: ${{ inputs.testToRun }}
      test_secrets_override_key: ${{ inputs.test_secrets_override_key || needs.set-test-secrets.outputs.test_secrets_override_key }}
      test_config_override_path: ${{ inputs.test_config_override_path }}
      # Fallback is used to properly convert a string to boolean 
      skip_image_build: ${{ needs.version-to-docker-registry.outputs.skip_image_build == 'true' && true || false }}
      SLACK_USER: ${{ inputs.slackMemberID }}
      team: ${{ inputs.team }}
    secrets:
      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
      PROD_AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      QA_PYROSCOPE_INSTANCE: ${{ secrets.QA_PYROSCOPE_INSTANCE }}
      QA_PYROSCOPE_KEY: ${{ secrets.QA_PYROSCOPE_KEY }}
      GRAFANA_INTERNAL_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
      GRAFANA_INTERNAL_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
      GRAFANA_INTERNAL_HOST: ${{ secrets.GRAFANA_INTERNAL_HOST }}
      GRAFANA_INTERNAL_URL_SHORTENER_TOKEN: ${{ secrets.GRAFANA_INTERNAL_URL_SHORTENER_TOKEN }}
      LOKI_TENANT_ID: ${{ secrets.LOKI_TENANT_ID }}
      LOKI_URL: ${{ secrets.LOKI_URL }}
      LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN }}
      AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}
      TEST_SECRETS_OVERRIDE_BASE64: ${{ secrets[inputs.test_secrets_override_key] }}
      SLACK_API_KEY: ${{ secrets.QA_SLACK_API_KEY }}
      SLACK_CHANNEL: ${{ secrets.QA_SLACK_CHANNEL }}
      MAIN_DNS_ZONE_PUBLIC_SDLC: ${{ secrets.MAIN_DNS_ZONE_PUBLIC_SDLC }}
      AWS_K8S_CLUSTER_NAME_SDLC: ${{ secrets.AWS_K8S_CLUSTER_NAME_SDLC }}
