name: On Demand OCR Soak Test
on:
  push:
    tags:
      # Run on release tags
      - 'v*'

  workflow_dispatch:
    inputs:
      testToRun:
        description: Test to run (from .github/e2e-tests.yml)
        required: true
        default: soak/ocr_test.go:TestOCRv2Soak
        type: choice
        options:
          - soak/ocr_test.go:TestOCRv1Soak
          - soak/ocr_test.go:TestOCRv2Soak
          - soak/ocr_test.go:TestForwarderOCRv1Soak
          - soak/ocr_test.go:TestForwarderOCRv2Soak
          - soak/ocr_test.go:TestOCRSoak_GethReorgBelowFinality_FinalityTagDisabled
          - soak/ocr_test.go:TestOCRSoak_GethReorgBelowFinality_FinalityTagEnabled
          - soak/ocr_test.go:TestOCRSoak_GasSpike
          - soak/ocr_test.go:TestOCRSoak_ChangeBlockGasLimit
          - soak/ocr_test.go:TestOCRSoak_RPCDownForAllCLNodes
          - soak/ocr_test.go:TestOCRSoak_RPCDownForHalfCLNodes
      chainlink_version:
        description: Version to test (e.g. "v2.25.0-beta.0", "develop", etc.)
        required: true
        default: develop
        type: string
      test_config_override_path:
        description: Path to the override test config TOML (defaults to OCR2 on Eth Sepolia, 12h soak)
        required: false
        default: 'integration-tests/testconfig/ocr2/overrides/ethereum_sepolia_12h.toml'
        type: string
      test_secrets_override_key:
        description: Test secrets (defaults to EOA - 0x663d14907663dC0D2bC3A3b9Ad61c10fa9B0fc08 on Eth Sepolia)
        required: false
        type: string
      team:
        description: Team (e.g. BIX, CCIP, CRE, etc.)
        required: true
        type: string
      slackMemberID:
        description: Slack Member ID (to tag when results published in `#test-run-notifications` Slack channel).
        required: true
        default: U01A2B2C3D4

jobs:
  # When running on a tag, wait for the image to be published to a registry
  wait-for-workflows:
    name: Wait for Release Image Build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref_name || github.sha }}

      - name: Wait for Image Build
        uses: smartcontractkit/.github/actions/wait-for-workflows@wait-for-workflows/1.0.0
        with:
          max-timeout: '900'
          polling-interval: '30'
          exclude-workflow-names: |
            Automation Nightly Tests
            Client Compatibility Tests
            Integration In-Memory Tests
            Integration Tests
          exclude-workflow-ids: ''
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: 'true'
  
  # Based on the `inputs.chainlink_version` define whether to:
  # - use a private or public ECR registry
  # - skip image build if public ECR registry is used
  version-to-docker-registry:
    name: Define Image Location Based on Version
    runs-on: ubuntu-latest
    outputs:
      skip_image_build: ${{ steps.set-registry-type.outputs.skip_image_build }}
    env:
      VERSION: ${{ inputs.chainlink_version || github.ref_name }}
    steps:
      - name: Select ECR registry (private or public) Based on Version
        id: set-registry-type
        shell: bash
        run: |
          # Ensure version is present (from input or tag name)
          if [[ -z "$VERSION" ]]; then
            echo "Error: version is not set. 'chainlink_version' input or GH tag is required."
            exit 1
          fi

          # Check if VERSION matches a public registry pattern (e.g., v2.26.0-beta.0)
          if [[ "$VERSION" =~ ^v[0-9]+\..*$ ]]; then
            echo "skip_image_build=true" >> $GITHUB_OUTPUT
            echo "Version '$VERSION' detected. Using PUBLIC ECR registry - no image build required."
          else
            echo "skip_image_build=false" >> $GITHUB_OUTPUT
            echo "Detected version: '$VERSION'. Using PRIVATE ECR registry - image build is required."
          fi

  # Prefix `v` should be stripped for Docker images
  resolve-docker-version:
    name: Resolve Version
    runs-on: ubuntu-latest
    needs: version-to-docker-registry
    outputs:
      chainlink_image_version: ${{ steps.resolve.outputs.chainlink_image_version }}
    env:
      VERSION: ${{ inputs.chainlink_version || github.ref_name }}
    steps:
      - name: Check if '${{ env.VERSION }}' is a 'Core' Release Version
        if: ${{ needs.version-to-docker-registry.outputs.skip_image_build == 'true' }}
        id: is-core
        run: |
          # Examples: `v2.23.1-beta.0`, `v2.23.1-rc.1`, `v2.23.1`
          if [[ "$VERSION" =~ v[0-9]+\.[0-9]+\.[0-9]+-beta.*$ || "$VERSION" =~ v[0-9]+\.[0-9]+\.[0-9]+-rc.*$ || "$VERSION" =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is-core=true" >> $GITHUB_OUTPUT
            echo "Version '$VERSION' is a 'core' release version."
          else
            echo "is-core=false" >> $GITHUB_OUTPUT
            echo "Version '$VERSION' is NOT a 'core' release version."
          fi

      - name: Resolve '${{ env.VERSION }}' version for Docker
        id: resolve
        shell: bash
        run: |
          if [[ ${{ steps.is-core.outputs.is-core == 'true' }} ]]; then
            # strip the `v` prefix from the version
            resolved_version="${VERSION#v}"
            echo "Resolved version for 'core' image: '$resolved_version' (stripped 'v' prefix)."
            echo "chainlink_image_version=$resolved_version" >> $GITHUB_OUTPUT
          else
            resolved_version="$VERSION"
            echo "Using image version as-is: '$resolved_version'."
            echo "chainlink_image_version=$resolved_version" >> $GITHUB_OUTPUT
          fi

  # Set provided or default test secrets
  set-test-secrets:
    name: Set Test Secrets
    runs-on: ubuntu-latest
    needs: version-to-docker-registry
    outputs:
      test_secrets_override_key: ${{ steps.test-secrets.outputs.test_secrets_override_key }}
    env:
      SECRETS_OVERRIDE_KEY: ${{ inputs.test_secrets_override_key }}
      SKIP_IMAGE_BUILD: ${{ needs.version-to-docker-registry.outputs.skip_image_build }}
      PUBLIC_ECR_DEFAULT_TEST_SECRETS: aws:testsecrets/DEFAULT_TEST_SECRETS
      PRIVATE_ECR_DEFAULT_TEST_SECRETS: aws:testsecrets/PRIVATE_DEFAULT_TEST_SECRETS
    steps:
      - name: Set Test Secrets (default or provided)
        id: test-secrets
        run: |
          if [[ -n "$SECRETS_OVERRIDE_KEY" ]]; then
            echo "Using explicitly provided test secrets."
            echo "test_secrets_override_key=$SECRETS_OVERRIDE_KEY" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "No 'test_secrets_override_key' provided. Selecting default based on image registry..."
          if [[ "$SKIP_IMAGE_BUILD" == 'true' ]]; then
            echo "test_secrets_override_key=$PUBLIC_ECR_DEFAULT_TEST_SECRETS" >> $GITHUB_OUTPUT
            echo "Using default secrets for PUBLIC ECR registry."
          else
            echo "test_secrets_override_key=$PRIVATE_ECR_DEFAULT_TEST_SECRETS" >> $GITHUB_OUTPUT
            echo "Using default secrets for PRIVATE ECR registry."
          fi

  run-e2e-tests-workflow:
    name: Run E2E Tests
    needs:
      - wait-for-workflows
      - resolve-docker-version
      - set-test-secrets
    # Run this job only if:
    # - optional wait-for-workflows did not fail (published release image might not be required),
    # - and the other dependencies were successful.
    if: >-
      always() &&
      needs.wait-for-workflows.result != 'failure' &&
      needs.resolve-docker-version.result == 'success' && needs.set-test-secrets.result == 'success'
    uses: smartcontractkit/.github/.github/workflows/run-e2e-tests.yml@7120f3a614452e1c6b84876c055f574011a947d1
    with:
      chainlink_version: ${{ needs.resolve-docker-version.outputs.chainlink_image_version }}
      test_path: .github/e2e-tests.yml
      test_ids: ${{ inputs.testToRun }}
      test_secrets_override_key: ${{ inputs.test_secrets_override_key || needs.set-test-secrets.outputs.test_secrets_override_key }}
      test_config_override_path: ${{ inputs.test_config_override_path }}
      # Fallback is used to properly convert a string to boolean 
      skip_image_build: ${{ needs.version-to-docker-registry.outputs.skip_image_build == 'true' && true || false }}
      SLACK_USER: ${{ inputs.slackMemberID }}
      team: ${{ inputs.team }}
    secrets:
      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
      PROD_AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      QA_PYROSCOPE_INSTANCE: ${{ secrets.QA_PYROSCOPE_INSTANCE }}
      QA_PYROSCOPE_KEY: ${{ secrets.QA_PYROSCOPE_KEY }}
      GRAFANA_INTERNAL_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
      GRAFANA_INTERNAL_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
      GRAFANA_INTERNAL_HOST: ${{ secrets.GRAFANA_INTERNAL_HOST }}
      GRAFANA_INTERNAL_URL_SHORTENER_TOKEN: ${{ secrets.GRAFANA_INTERNAL_URL_SHORTENER_TOKEN }}
      LOKI_TENANT_ID: ${{ secrets.LOKI_TENANT_ID }}
      LOKI_URL: ${{ secrets.LOKI_URL }}
      LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN }}
      AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}
      TEST_SECRETS_OVERRIDE_BASE64: ${{ secrets[needs.set-test-secrets.outputs.test_secrets_override_key] }}
      SLACK_API_KEY: ${{ secrets.QA_SLACK_API_KEY }}
      SLACK_CHANNEL: ${{ secrets.QA_SLACK_CHANNEL }}
      MAIN_DNS_ZONE_PUBLIC_SDLC: ${{ secrets.MAIN_DNS_ZONE_PUBLIC_SDLC }}
      AWS_K8S_CLUSTER_NAME_SDLC: ${{ secrets.AWS_K8S_CLUSTER_NAME_SDLC }}
      OPTIONAL_GATI_AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_GLOBAL_READ_ONLY_TOKEN_ISSUER_ROLE_ARN }}
      OPTIONAL_GATI_LAMBDA_URL: ${{ secrets.AWS_INFRA_RELENG_TOKEN_ISSUER_LAMBDA_URL }}
