name: "Post Build, Sign and Publish Chainlink"
on:
    # # to be used with pre-release tests
    repository_dispatch:
        types: [ pre-release-image-published ]

permissions: {}

jobs:
    validate-trigger:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Validate trigger
              env:
                  CHAINLINK_IMAGE_TAG: ${{ github.event.client_payload.chainlink_image_tag }}
                  CHAINLINK_VERSION: ${{ github.event.client_payload.chainlink_version }}
              run: |
                  echo "Image Tag: $CHAINLINK_IMAGE_TAG"
                  echo "Chainlink Version: $CHAINLINK_VERSION"
                  if [ -z "$CHAINLINK_IMAGE_TAG" ]; then
                      echo "Chainlink image tag is required, but 'client_payload.chainlink_image_tag' is empty"
                      exit 1
                  fi
                  if [ -z "$CHAINLINK_VERSION" ]; then
                      echo "Chainlink Version is required, but 'client_payload.chainlink_version' is empty"
                      exit 1
                  fi
                  if [[ "$CHAINLINK_VERSION" != v* ]]; then
                      echo "This workflow can only be used with semver tags, 'chainlink_version' must begin with 'v', got: $CHAINLINK_VERSION"
                      exit 1
                  fi
                  echo "Trigger validated successfully"
    # Upgrade compatibility tests
    # Include rc and beta releases, since we will be upgrading from them on canary servers
    df1-compat:
        uses: ./.github/workflows/devenv-compat.yml
        name: Data Feeds v1 Upgrade Test
        needs: validate-trigger
        permissions:
            id-token: write
            contents: read
        with:
            buildcmd: "just cli"
            envcmd: "cl u env.toml,products/ocr2/basic.toml"
            testcmd: "cl test ocr2 TestSmoke/rounds"
            upgrade-nodes: "3"
            node-name-template: "don-node%d"
            versions-back: "3"
            exclude-refs: "ccip"
            working-directory: "devenv"
            logs-directory: "./devenv/tests/ocr2/logs"
            ctf-log-level: "debug"
            strip-image-suffix: "v"
            tag-version-ceiling: ${{ github.event.client_payload.chainlink_version }}
        secrets: inherit

    cre-compat:
        uses: ./.github/workflows/devenv-compat.yml
        name: CRE Upgrade Test
        needs: validate-trigger
        permissions:
            id-token: write
            contents: read
        with:
            buildcmd: "echo nothing-to-build" # added to prevent `just cli` from being used (default buildcmd if not provided)
            envcmd: "go run -C ../../core/scripts/cre/environment . env start"
            testcmd: "go test -v -run Test_Upgrade_Suite ./smoke/cre"
            upgrade-nodes: "3"
            node-name-template: "workflow-node%d"
            versions-back: "3"
            exclude-refs: "ccip"
            working-directory: "./system-tests/tests"
            logs-directory: "./system-tests/tests/smoke/cre/logs"
            ctf-log-level: "debug"
            strip-image-suffix: "v"
            tag-version-ceiling: ${{ github.event.client_payload.chainlink_version }}
        secrets: inherit

    legacy-system-tests:
        name: Legacy Smoke Tests
        needs: validate-trigger
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/legacy-system-tests.yml
        with:
            ecr: "public"
            chainlink_version: ${{ github.event.client_payload.chainlink_version }}
            chainlink_image_repository_path: "chainlink/chainlink"
            chainlink_image_tag: ${{ github.event.client_payload.chainlink_image_tag }}
        secrets: inherit

    cre-smoke-tests:
        name: CRE Smoke Tests
        needs: validate-trigger
        permissions:
            actions: read
            contents: read
            id-token: write
        uses: ./.github/workflows/cre-system-tests.yaml
        with:
            ecr: "public"
            chainlink_version: ${{ github.event.client_payload.chainlink_version }}
            chainlink_image_repository_path: "chainlink/chainlink"
            chainlink_image_tag: ${{ github.event.client_payload.chainlink_image_tag }}
        secrets: inherit

    cre-regression-tests:
        name: CRE Regression Tests
        needs: validate-trigger
        permissions:
            actions: read
            contents: read
            id-token: write
        uses: ./.github/workflows/cre-regression-system-tests.yaml
        with:
            ecr: "public"
            chainlink_version: ${{ github.event.client_payload.chainlink_version }}
            chainlink_image_repository_path: "chainlink/chainlink"
            chainlink_image_tag: ${{ github.event.client_payload.chainlink_image_tag }}
        secrets: inherit

    # Slack notifications
    # Only executed, if the slack thread timestamp is provided in the event payload.
    df1-compat-notify:
        runs-on: ubuntu-latest
        needs: [ df1-compat ]
        if: always() && github.event.client_payload.slack_thread_ts
        steps:
            - name: Notify Slack Jobs Result
              uses: ./.github/actions/notify-slack-jobs-result
              with:
                  status: ${{ needs.df1-compat.result }}
                  job_name: "Data Feeds v1 Upgrade Test"
                  run_url: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url,
                      github.repository, github.run_id) }}
                  slack_thread_ts: ${{ github.event.client_payload.slack_thread_ts }}
                  slack_channel_id: ${{ secrets.SLACK_CHANNEL_RELEASE_NOTIFICATIONS }}
                  slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }}

    cre-compat-notify:
        runs-on: ubuntu-latest
        needs: [ cre-compat ]
        if: always() && github.event.client_payload.slack_thread_ts
        steps:
            - name: Notify Slack Jobs Result
              uses: ./.github/actions/notify-slack-jobs-result
              with:
                  status: ${{ needs.cre-compat.result }}
                  job_name: "CRE Upgrade Test"
                  run_url: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url,
                      github.repository, github.run_id) }}
                  slack_thread_ts: ${{ github.event.client_payload.slack_thread_ts }}
                  slack_channel_id: ${{ secrets.SLACK_CHANNEL_RELEASE_NOTIFICATIONS }}
                  slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }}

    legacy-system-tests-notify:
        runs-on: ubuntu-latest
        needs: [ legacy-system-tests ]
        if: always() && github.event.client_payload.slack_thread_ts
        steps:
            - name: Notify Slack Jobs Result
              uses: ./.github/actions/notify-slack-jobs-result
              with:
                  status: ${{ needs.legacy-system-tests.result }}
                  job_name: "Legacy Smoke Tests"
                  run_url: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url,
                      github.repository, github.run_id) }}
                  slack_thread_ts: ${{ github.event.client_payload.slack_thread_ts }}
                  slack_channel_id: ${{ secrets.SLACK_CHANNEL_RELEASE_NOTIFICATIONS }}
                  slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }}

    cre-smoke-tests-notify:
        runs-on: ubuntu-latest
        needs: [ cre-smoke-tests ]
        if: always() && github.event.client_payload.slack_thread_ts
        steps:
            - name: Notify Slack Jobs Result
              uses: ./.github/actions/notify-slack-jobs-result
              with:
                  status: ${{ needs.cre-smoke-tests.result }}
                  job_name: "CRE Smoke Tests"
                  run_url: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url,
                      github.repository, github.run_id) }}
                  slack_thread_ts: ${{ github.event.client_payload.slack_thread_ts }}
                  slack_channel_id: ${{ secrets.SLACK_CHANNEL_RELEASE_NOTIFICATIONS }}
                  slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }}

    cre-regression-tests-notify:
        runs-on: ubuntu-latest
        needs: [ cre-regression-tests ]
        if: always() && github.event.client_payload.slack_thread_ts
        steps:
            - name: Notify Slack Jobs Result
              uses: ./.github/actions/notify-slack-jobs-result
              with:
                  status: ${{ needs.cre-regression-tests.result }}
                  job_name: "CRE Regression Tests"
                  run_url: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url,
                      github.repository, github.run_id) }}
                  slack_thread_ts: ${{ github.event.client_payload.slack_thread_ts }}
                  slack_channel_id: ${{ secrets.SLACK_CHANNEL_RELEASE_NOTIFICATIONS }}
                  slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }}
