name: Run Nightly In-Memory Integration Tests

on:
  schedule:
    # Run every night at midnight UTC (0:00 AM)
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Useful when running the workflow manually
    inputs:
      chainlink_version:
        description: 'Enter Chainlink version to use for the tests. Example: "v2.10.0" or sha'
        required: true
        type: string
        default: develop

jobs:
  in-memory-tests:
    uses: ./.github/workflows/integration-in-memory-tests.yml
    with:
      chainlink_version: ${{ inputs.chainlink_version || 'develop' }}
      slack_channel_id: "#team-test-tooling-internal"
    secrets: inherit
