name: Solidity

on:
  merge_group:
  push:

defaults:
  run:
    shell: bash

jobs:
  readonly_changes:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  changes:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  tag-check:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  prepublish-test:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  native-compile:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  # The if statements for steps after checkout repo is a workaround for
  # passing required check for PRs that don't have filtered changes.
  lint:
    name: Solidity Lint
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  prettier:
    name: Prettier Formatting
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  publish-beta:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  publish-prod:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"