name: Solidity
on:
  merge_group:
  push:

jobs:
  lint:
    if: always()
    name: Solidity Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  prettier:
    if: always()
    name: Prettier Formatting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"