name: Solidity Foundry
on:
  pull_request:
  merge_group:

jobs:
  define-matrix:
    if: always()
    name: Define test matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success"

  check-tests-results:
    if: always()
    name: Check Foundry Tests Results
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Success'

  check-fmt-results:
    if: always()
    name: Check Foundry Format Results
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Success'
